import {h} from "../ui/dom.js";
import {tex} from "../ui/math.js";
import {chapterHeader,chapterFooter,topic,prose,equation,proof,table,optional,bookReading,reading} from "./shell.js";
import {stateLab,bellmanLab,featureLab} from "./labs.js";
export function mdp(root){
  root.append(chapterHeader("01"),
    topic("01","task",
      prose("小车从p=2 m出发，在p=0附近停稳；每0.5秒选择连续推力u，既要接近目标，也要及时刹车。",
        "同位置、同推力下，v=+1与v=−1产生不同后继，因此状态需包含速度。"),
      stateLab(),
      equation("s_t=(p_t,v_t),\\quad u_t\\in\\mathbb R,\\quad s_{t+1}\\sim P(\\cdot\\mid s_t,u_t),\\quad u_t\\sim\\pi(\\cdot\\mid s_t)",
        "π选择动作，P给出下一状态的分布。"),
      table(["MDP对象","符号与公式","小车中的含义"],[
        [h("span",{},"状态 ",tex("\\mathcal S")),tex("s_t=(p_t,v_t)\\in\\mathcal S=\\mathbb R^2"),"位置与速度"],
        [h("span",{},"动作 ",tex("\\mathcal A")),tex("a_t=u_t\\in\\mathcal A=\\mathbb R"),"一个采样周期内的推力"],
        [h("span",{},"转移 ",tex("P")),tex("P(\\cdot\\mid s_t,u_t)=\\delta_{f(s_t,u_t)}"),"下一状态确定为f(sₜ,uₜ)"],
        [h("span",{},"reward ",tex("r")),tex("r(s_t,u_t)=-(p_t-g)^2-0.2v_t^2-0.5u_t^2"),"接近目标、停稳、少用力；g=0"],
        [h("span",{},"初始分布 ",tex("\\rho_0")),tex("s_0\\sim\\rho_0,\\quad\\rho_0=\\delta_{(2,0)}"),"默认从2 m静止出发"],
      ]),
      equation("\\boxed{\\begin{aligned}p_{t+1}&=p_t+v_t\\Delta t+\\frac{u_t}{2m}\\Delta t^2\\\\v_{t+1}&=v_t+\\frac{u_t}{m}\\Delta t\\end{aligned}}\\qquad s_{t+1}=f(s_t,u_t)",
        "牛顿第二定律＋匀加速运动：m=1 kg、Δt=0.5 s，每步推力恒定，忽略摩擦。"),
      prose(h("span",{},tex("\\delta_x"),"表示状态确定为x；有限时域再把剩余步数H−t加入状态。"),
        "Markov性：给定当前状态和动作，下一状态与更早的历史无关。")),
    topic("01","values",
      prose("持续向左推可能高速穿过目标；速度反馈让小车提前反向刹车，整条轨迹的return决定哪种策略更好。",
        "我们把“接近目标、停稳、少用力”写成每步reward："),
      equation("e_t=p_t-g,\\qquad r_t=\\underbrace{-e_t^2}_{\\text{接近目标}}\\underbrace{-0.2v_t^2}_{\\text{停稳}}\\underbrace{-0.5u_t^2}_{\\text{少用力}}",
        "pₜ是第t步的位置，g是目标位置；rₜ按当前状态和本步推力计算。其他项不变时，误差、速度或推力的绝对值越小，reward越高；系数是任务设置。"),
      prose("例如在目标处、没有推力时：v=0得到r=0；v=1得到r=−0.2。到达位置但仍在运动，reward就更低。",
        "任务执行H次动作，默认H=6，即3秒；最后根据状态s_H再给一次末端reward："),
      equation("r_H=\\underbrace{-20(p_H-g)^2}_{\\text{最后到达目标}}\\underbrace{-10v_H^2}_{\\text{最后停稳}}",
        "末端权重更大，强调最后到达并停稳；此时不再选择推力u_H。例如p_H=g、v_H=1时，r_H=−10。"),
      equation("G_0=\\sum_{t=0}^{H-1}r_t+r_H\\qquad(\\gamma=1)",
        "这个停车任务的return是各步reward加一次末端reward。"),
      prose("初态(p,v)=(2,0)时，u=0得到r=−4，u=−1得到r=−4.5；用力降低眼前reward，却能减小后续误差，所以策略比较整条未来。"),
      equation("G_t=\\sum_{k\\ge0}\\gamma^kr_{t+k},\\qquad J(\\pi)=\\mathbb E_{s_0\\sim\\rho_0,\\pi}G_0,\\qquad \\pi^*\\in\\arg\\max_\\pi J(\\pi)",
        "G是轨迹return，J是从ρ₀出发的期望return；γ决定远期reward的权重。"),
      equation("V^\\pi(s)=\\mathbb E_\\pi[G_t\\mid s_t=s],\\qquad Q^\\pi(s,a)=\\mathbb E_\\pi[G_t\\mid s_t=s,a_t=a]",
        "V从当前状态按π行动，Q先指定a再按π行动；两者都是期望return。"),
      prose("有限时域记Vₜ：还剩1步与6步可能需要不同推力；无限折扣用γ<1，第9章有限时域用γ=1并计入末端reward。")),
    topic("01","bellman",
      prose("我们要找使期望return最大的策略。Bellman的思路是：知道下一状态的后续价值，就能比较现在的动作。"),
      proof("先看一个完整的小任务","1 · 今天移动一次，明天领取末端reward",
        prose("先用一维位置调整任务：e是离目标的误差，动作a直接表示移动距离。只剩一次动作，之后任务结束；γ=1。"),
        equation("e_{t+1}=e_t+a,\\qquad r_t=-e_t^2-0.5a^2,\\qquad V_{t+1}^*(e')=r_{t+1}(e')=-\\kappa e'^2",
          "末端已无动作，所以V就是末端reward；κ是给定的末端权重。这里a是位移，第1.1的小车动作u才是推力。"),
        prose("从e=2出发，κ=4。不移动得到−4−16=−20；移动−2恰好到达目标，得到−6+0=−6；移动−1得到−4.5−4=−8.5。每个数字都包括当前reward和末端reward。"),
        equation("Q_t^*(2,a)=\\underbrace{-4-0.5a^2}_{\\text{当前reward}}\\underbrace{-4(2+a)^2}_{\\text{末端价值}},\\qquad V_t^*(2)=\\max_a Q_t^*(2,a)",
          "Q评价一个指定动作，V取所有动作中的最大Q。连续动作还可选−1.778，不能只比较表里的整数。"),
        bellmanLab(),
        equation("\\frac{\\partial Q_t^*(e,a)}{\\partial a}=-a-2\\kappa(e+a)=0\\quad\\Longrightarrow\\quad a^*=-\\frac{\\kappa}{0.5+\\kappa}e",
          "二阶导数为−1−2κ<0，所以这是最大值。e=2、κ=4时，a*=−16/9，Vₜ*(2)=−52/9≈−5.778。"),
        prose("最优动作留下少量误差，换取更高的当前reward。若还剩更多步，就先算最后一步的V，再逐步往前算；第9章对完整小车状态(p,v)做同样的递推。")),
      proof("从算例推广到任意轨迹","2 · 把return拆成第一步与余下未来",
        equation("\\begin{aligned}G_t&=r_t+\\gamma r_{t+1}+\\gamma^2r_{t+2}+\\cdots\\\\&=r_t+\\gamma\\underbrace{(r_{t+1}+\\gamma r_{t+2}+\\cdots)}_{G_{t+1}}\\\\&=r_t+\\gamma G_{t+1}\\end{aligned}",
          "只是把return的第一项提出；后面的所有reward仍包含在Gₜ₊₁中。"),
        prose("一般环境的后继可能随机，策略的未来动作也可能随机，因此要对这条关系取期望。下面写无限折扣形式；有限时域给V、Q加上t和t+1，分解相同。")),
      proof("先解释为什么关心V与Q","3 · 从任务目标到V/Q，再推Bellman期望方程",
        prose("动力学决定动作会带到什么状态，reward规定这些结果怎样评分。我们选择的任务目标是最大化期望return："),
        equation("\\max_\\pi J(\\pi),\\qquad J(\\pi)=\\mathbb E_{s_0\\sim\\rho_0,\\pi}[G_0]=\\mathbb E_{s_0\\sim\\rho_0}[V^\\pi(s_0)]",
          "Vπ从一个状态出发评价策略；按相同初始分布ρ₀平均这些评分，就是我们要优化的J。"),
        equation("G_0=\\underbrace{\\sum_{k=0}^{t-1}\\gamma^kr_k}_{\\text{已经发生}}+\\gamma^t\\underbrace{G_t}_{\\text{尚可影响的未来}}",
          "当前动作不能改变已发生的reward，所以现在要比较的是余下未来的期望return。"),
        prose("先固定后续策略π，只改变当前动作a。这样比较的“本步选a，之后执行π”的期望return，正是Qπ(s,a)；保持后续相同，才能判断这一步动作的影响。",
          "小车在(p,v)=(0.5,−1)，正向左接近目标g=0；只剩最后一次0.5 s动作。γ=1，末端reward沿用1.2："),
        table(["候选推力u","当前reward rₜ","后继(p′,v′)","整条未来的Qₜπ"],[
          ["−1 N · 向左加速","−0.95","(−0.125,−1.5)","−23.7625"],
          ["+1 N · 向右刹车","−0.95","(0.125,−0.5)","−3.7625"],
        ]),
        prose("两者当前reward相同；加入末端reward后，这两个候选中刹车的return更高。表中Qₜπ=rₜ+r_H；动力学确定，所以期望就是算出的return。Q把动作导致的后续结果也纳入了比较。",
          "接下来对Gₜ=rₜ+γGₜ₊₁取期望。给定完整状态s′，按π行动的余下return期望就是Vπ(s′)；这一步使用Markov性。"),
        equation("\\begin{aligned}Q^\\pi(s,a)&=\\mathbb E_\\pi[G_t\\mid s_t=s,a_t=a]\\\\&=\\mathbb E_\\pi[r_t+\\gamma G_{t+1}\\mid s_t=s,a_t=a]\\\\&=\\mathbb E_{r,s'\\mid s,a}\\!\\left[r+\\gamma\\underbrace{\\mathbb E_\\pi[G_{t+1}\\mid s_{t+1}=s']}_{V^\\pi(s')}\\right]\\\\&=\\mathbb E_{r,s'\\mid s,a}[r+\\gamma V^\\pi(s')]\\end{aligned}",
          "第二行拆return；第三行先算给定s′的未来期望，再平均本步后果；第四行代入Vπ的定义。"),
        prose("Vπ没有指定第一步动作；它还要按π选择动作的概率，对Qπ取平均。"),
        equation("V^\\pi(s)=\\mathbb E_{a\\sim\\pi(\\cdot\\mid s)}Q^\\pi(s,a)=\\mathbb E_{a\\sim\\pi,\\ r,s'\\mid s,a}[r+\\gamma V^\\pi(s')]",
          "确定性策略只取a=π(s)这一项；随机策略对可能的动作加权平均。Vπ给出原策略在此状态的平均评分。"),
        prose("Qπ(s,a)>Vπ(s)表示：本步改选a、以后仍执行π，期望return比原策略更高。这为策略改进提供依据；后续π还没优化，因此Qπ不自动等于Q*。",
          "Bellman把同一个长期评分写成“一步reward＋后继价值”的递推形式，来自return的加法结构与迭代期望。若已知Vπ(s′)，就能用它概括按π行动的全部后续。")),
      proof("再寻找最优策略π*","4 · 后续也最优，当前动作才取最大Q",
        prose("到达s′后，若能换成return更高的后续策略，整条未来也会更好。因此最优策略从s′开始仍应最优，这就是最优性原理。",
          "Q*固定当前动作，后续采用最优策略；V*再选当前最好的动作。这里的后续V*也必须求出来。"),
        equation("Q^*(s,a)=\\mathbb E_{r,s'\\mid s,a}[r+\\gamma V^*(s')],\\qquad V^*(s)=\\max_a Q^*(s,a),\\qquad \\pi^*(s)\\in\\arg\\max_aQ^*(s,a)",
          "max给出最优价值，arg max给出实现这个价值的动作；连续动作的最大值未达到时用sup。"),
        prose("将Q*代入V*，得到V形式的Bellman最优方程："),
        equation("\\boxed{V^*(s)=\\max_a\\mathbb E_{r,s'\\mid s,a}[r+\\gamma V^*(s')]}",
          "先为每个动作计算“当前reward＋最优后续价值”的期望，再选最大值；不能先看到随机后继再反过来选当前动作。"),
        prose("将V*(s′)=max Q*(s′,a′)代入Q*，得到Q形式："),
        equation("\\boxed{Q^*(s,a)=\\mathbb E_{r,s'\\mid s,a}[r+\\gamma\\max_{a'}Q^*(s',a')]}",
          "下一动作a′在到达s′后选择，所以它的max在期望里面。"),
        prose("固定策略的方程按π平均；最优方程让后续也最优，并选择最大Q。第一个算例正是已知末端Vₜ₊₁*后，求当前Qₜ*和Vₜ*的一次Bellman备份。")),
      proof("方程怎样变成学习算法","5 · Q-learning用一个样本构造Bellman目标",
        prose("知道模型时，可以计算上式的环境期望。模型未知时，执行(s,a)，观察(r,s′)，用当前估计Q̂构造一个样本目标："),
        equation("y=r+\\gamma\\max_{a'}\\widehat Q(s',a'),\\qquad\\widehat Q(s,a)\\leftarrow\\widehat Q(s,a)+\\eta[y-\\widehat Q(s,a)]",
          "y−Q̂是TD error；更新把当前估计向“本步reward＋估计的最优后续”移动。η是学习率，单个样本仍有噪声。"),
        prose("例如Q̂(s,a)=−10，r=−1，后继最大Q̂=−4，γ=0.9：y=−4.6；η=0.1时更新为−9.46。只有本步数据来自新观察，后续价值来自已有估计，这叫bootstrap。",
          h("span",{},"真终止时y=r，末端reward计入这次r；外部截断仍接后续价值。",h("a",{href:"#chapter-02/updates"},"第2章比较TD、SARSA与Q-learning →")))),
      optional("Bellman关系与训练目标",
        prose("Bellman是价值递推的核心，但训练可以采用其他目标：第5章REINFORCE直接用采样return；蒙特卡洛Contrastive RL用未来状态构造对比目标，不使用TD目标，而其对应的Q仍满足Bellman关系。",
          h("span",{},"其他对比RL方法可以使用TD；这里特指蒙特卡洛版本。",h("a",{href:"#chapter-10/relabel"},"第10章：未来占用与对比学习 →"))),
        reading("Ben论文 §3.4：Monte Carlo Contrastive RL","https://www.ml.cmu.edu/research/phd-dissertation-pdfs/thesis_eysenbach.pdf#page=44")),
      bookReading("§1.1.2–1.1.3：Bellman期望与最优方程",5)),
    topic("01","planning",
      table(["方法","固定或读取什么","更新什么"],[
        ["策略评价","固定π","计算Vπ或Qπ"],
        ["策略改进","读取Qπ","选取最大Qπ的动作"],
        ["策略迭代","循环评价与改进","更新策略，区别于梯度更新"],
        ["价值迭代","读取旧V的最优后续","V←TV，再提取贪心策略"],
      ]),
      equation("(TV)(s)=\\max_a\\mathbb E[r+\\gamma V(s')\\mid s,a],\\qquad \\|TV-TU\\|_\\infty\\le\\gamma\\|V-U\\|_\\infty",
        "有限表格、有界reward、γ<1时，收缩保证唯一最优固定点；无界二次reward需另行分析。"),
      equation("V_t^*(s)=\\max_a\\mathbb E[r_t+V_{t+1}^*(s')\\mid s,a],\\qquad V_H(s)=r_H(s)",
        "有限时域从末端reward倒推；第9章Riccati在二次价值函数中完成这一递推。"),
      optional("选读：线性规划、复杂度与性能差",
        prose("线性规划与算法复杂度见§1.3–1.5；性能差恒等式用于第7章策略更新。"),bookReading("§1.3–1.5",11)),
      bookReading("第1章",3)),
    chapterFooter("01","已知模型时，Bellman递推把整条未来的期望return转化为逐步规划。"));
  return()=>{};
}
export function data(root){
  root.append(chapterHeader("02"),
    topic("02","access",
      prose("学习Bellman期望需要(s,a,r,s′)样本。先分清两个问题：训练时能否继续采新数据？采样时能否直接指定状态？"),
      proof("数据是否继续增加","1 · 数据固定，还是允许继续采样？",
        table(["训练设置","数据权限","小车例子"],[
          ["Online轨迹交互","训练期间可继续与环境交互，收集新样本","开车、记录结果、更新策略，再继续开车"],
          ["Offline RL","训练只使用预先收集的固定数据集D","只读已有驾驶日志，不能为新策略补采数据"],
        ]),
        prose("数据来自真机还是模拟器，不决定online/offline；关键是训练期间是否允许继续收集新环境数据。")),
      proof("新样本怎样取得","2 · 沿轨迹采样，还是直接查询任意状态动作？",
        table(["采样权限","能选择什么","小车例子"],[
          ["沿轨迹交互","在当前状态选择动作；下一状态由环境产生","从(2,0)出发，想在(1,−1)采样，需先实际到达该状态"],
          ["Generative model / 采样oracle","直接指定任意合法(s,a)，取得独立的环境样本","直接把模拟器设为(1,−1)，测试推力u=+1；可重新设定后重复测试"],
        ]),
        equation("\\operatorname{Sample}(s,a)\\longrightarrow(r,s'),\\qquad s'\\sim P(\\cdot\\mid s,a)",
          "这里generative model指环境采样器：输入状态和动作，返回reward与后继；P的公式可以未知。"),
        prose("采样oracle省去了“先开到要测试的状态”这一步，所以理论上能单独研究采样精度；沿轨迹交互还必须解决探索和可达性。",
          "普通reset只回到初始分布，不自动提供oracle权限；oracle须支持从任意指定的合法完整状态采样。有限时域还要指定阶段t。")),
      proof("为什么教材会把三者并列","3 · 比较的是数据访问假设",
        prose("教材并列的是三种权限：只读日志、沿轨迹采新样本、任意查询采新样本。Online/offline强调能否继续采集，generative model强调能怎样采集；不能把三个名称当作互斥的训练标签。",
          "先用oracle生成一份数据，封存后只用它训练，仍是offline。用replay buffer且持续收集新数据，仍是online；replay本身不会增加任意查询权限。"),
        bookReading("§1.4：采样模型；第2章：generative model",17))),
    topic("02","statistics",
      equation("\\widehat{PV}(s,a)=\\frac1n\\sum_{i=1}^nV(s_i'),\\qquad \\operatorname{Var}(\\widehat{PV})=\\frac{\\operatorname{Var}(V(S'))}{n}",
        "固定V，在同一(s,a)独立采样，标准差随1/√n下降。"),
      prose("同一制动力下，后继V以各1/2概率为0或2，均值1、方差1；平均4个独立后继的方差为1/4，100个为1/100。样本精度与状态动作覆盖是两件事。",
        "若真实与估计算子在相关有界函数上均相差至多ε，且均为γ收缩（γ<1），固定点误差满足下式。"),
      equation("\\|\\hat V^*-V^*\\|_\\infty\\le\\frac{\\epsilon}{1-\\gamma}",
        "γ=0.9、0.99时分别放大10、100倍；样本复杂度还取决于reward界、覆盖、置信度与采样接口。"),
      optional("选读：minimax样本复杂度",
        prose("第2章给出方差分析与近最优样本数量；结论适用于其表格、采样oracle与有界reward假设。"),bookReading("第2章",21))),
    topic("02","updates",
      prose("第1章写出了价值必须满足的期望关系。现在模型未知，要决定：评价哪种策略？用哪些样本代替期望？未来用实际return，还是已有价值估计？"),
      table(["方法","出发点","怎样估计未来"],[
        ["MC","Vπ=Eπ[G]；也可将Bellman展开到终止","观察完整return"],
        ["TD(0)","固定π的V形式Bellman方程","一步样本＋估计的Vπ"],
        ["SARSA","当前π的Q形式Bellman方程","一步样本＋按π采样的下一动作Q"],
        ["Q-learning","Q*的Bellman最优方程","一步样本＋后继最大的估计Q"],
      ]),
      prose("下面先讲普通on-policy的MC、TD和SARSA：采样动作的策略就是被评价的π。Q-learning则允许用另一行为策略b收集数据。mₜ=0表示真正终止，mₜ=1表示仍有后续，包括外部截断。"),
      proof("相同的增量更新，不同的目标y","1 · 为什么有“旧估计＋学习率×误差”？",
        equation("\\begin{aligned}\\widehat V(s_t)&\\leftarrow\\widehat V(s_t)+\\eta[y_t-\\widehat V(s_t)]\\\\\\widehat Q(s_t,a_t)&\\leftarrow\\widehat Q(s_t,a_t)+\\eta[y_t-\\widehat Q(s_t,a_t)]\\end{aligned}",
          "帽子表示当前估计。η控制向样本目标移动多少；对同一条目第N次更新取η=1/N，就是普通样本平均。"),
        prose("Bellman给出要满足的期望关系；采样规则给出y；增量更新再把样本信息写入V或Q。下面分别推导四种y。")),
      proof("固定π＋完整回合＋样本平均","2 · MC：把未来全部展开，再观察完整return",
        equation("G_t=r_t+\\gamma G_{t+1}=r_t+\\gamma r_{t+1}+\\cdots+\\gamma^{T-t-1}r_{T-1},\\qquad V^\\pi(s)=\\mathbb E_\\pi[G_t\\mid s_t=s]",
          "递归展开到真正终止时刻T，后面不再有reward；末端reward已计入最后一次转移的r。"),
        equation("y_t^{\\mathrm{MC}}=G_t,\\qquad\\widehat V(s_t)\\leftarrow\\widehat V(s_t)+\\eta[G_t-\\widehat V(s_t)]",
          "用一次观察到的G代替Eπ[G]。第一访问MC每回合对同一状态只用第一次访问的return。"),
        prose("需要实际看到回合结束，并让后续动作来自π。MC直接估计价值定义中的期望，不需要后继V的估计，也不做bootstrap；完整return也可以用来估计Qπ(s,a)。",
          "这一步是在评价π。若要寻找最优策略，还需用学到的Q改进动作选择。")),
      proof("固定π＋一步环境样本＋后继V估计","3 · TD(0)：未来只展开一步",
        equation("V^\\pi(s)=\\mathbb E_\\pi[r+\\gamma V^\\pi(s')\\mid s]\\quad\\Longrightarrow\\quad y_t^{\\mathrm{TD}}=r_t+\\gamma m_t\\widehat V(s_{t+1})",
          "当前动作按π采样；用观察到的(rₜ,sₜ₊₁)代替环境与动作期望，用V̂代替未知Vπ。"),
        equation("\\delta_t=y_t^{\\mathrm{TD}}-\\widehat V(s_t),\\qquad\\widehat V(s_t)\\leftarrow\\widehat V(s_t)+\\eta\\delta_t",
          "δₜ是TD error；拿到下一状态就能更新，不必等整条未来结束。"),
        prose("只有rₜ是本步真实reward；未来由当前V̂预测，这就是bootstrap。y的期望是对当前V̂的一次Bellman备份，通常还不是Vπ。固定π时，TD(0)评价Vπ，并不会仅凭这条更新自动得到V*。")),
      proof("Qπ的Bellman关系＋按同一π采下一动作","4 · SARSA：把动作期望换成实际下一动作",
        equation("Q^\\pi(s,a)=\\mathbb E_{r,s'\\mid s,a}\\!\\left[r+\\gamma\\underbrace{\\sum_{a'}\\pi(a'\\mid s')Q^\\pi(s',a')}_{\\text{按}\\pi\\text{平均下一动作}}\\right]",
          "从Qπ出发，后继动作仍由π决定；这里先写离散动作，连续动作时把求和换成积分。"),
        equation("a_{t+1}\\sim\\pi(\\cdot\\mid s_{t+1})\\quad(m_t=1),\\qquad y_t^{\\mathrm{SARSA}}=r_t+\\gamma m_t\\widehat Q(s_{t+1},a_{t+1})",
          "用按π采到的aₜ₊₁代替动作期望；正常继续时，它就是下一步实际执行的动作，包含π的探索选择。真终止时直接取y=r，不采下一动作。"),
        equation("\\widehat Q(s_t,a_t)\\leftarrow\\widehat Q(s_t,a_t)+\\eta\\left[r_t+\\gamma m_t\\widehat Q(s_{t+1},a_{t+1})-\\widehat Q(s_t,a_t)\\right]",
          "名字来自使用的五元组：State、Action、Reward、State、Action。"),
        prose("采样策略与被评价策略相同，所以是on-policy。用于控制时，常按当前Q构造ε-greedy策略：大部分时候选最大Q，少部分时候探索；SARSA把这种探索的后果也计入未来。")),
      proof("最优Bellman关系＋环境样本＋后继max","5 · Q-learning：学习目标中的后续是贪心选择",
        equation("Q^*(s,a)=\\mathbb E_{r,s'\\mid s,a}\\!\\left[r+\\gamma\\max_{a'}Q^*(s',a')\\right]\\quad\\Longrightarrow\\quad y_t^{\\mathrm{QL}}=r_t+\\gamma m_t\\max_{a'}\\widehat Q(s_{t+1},a')",
          "采样只替代环境期望；max仍来自最优性原理。用Q̂近似Q*，不需要采一个实际下一动作来构造目标。"),
        equation("\\widehat Q(s_t,a_t)\\leftarrow\\widehat Q(s_t,a_t)+\\eta\\left[r_t+\\gamma m_t\\max_{a'}\\widehat Q(s_{t+1},a')-\\widehat Q(s_t,a_t)\\right]",
          "实际行为b可以探索；目标假设下一步选最大的Q̂，所以行为策略和目标策略可以不同，这叫off-policy。"),
        prose("给定(s,a)，reward与后继的条件分布由环境规定，与选择动作的策略b无关；因此探索策略采到的一步样本，也可用于最优Bellman备份。需要b确实访问那些要学习的状态动作。",
          "Off-policy不等于offline：前者比较行为与学习目标的策略，后者说明训练只能读取固定日志。小车动作连续时，max还需要优化整个推力空间。")),
      proof("放在同一条轨迹上比较","6 · 同一数据，为什么会得到不同目标？",
        h("div",{class:"physical-flow"},h("span",{},"s₀"),h("b",{},"→ r₀=−1 →"),h("span",{},"s₁"),h("b",{},"→ r₁=2 →"),h("span",{},"真正终止")),
        prose("γ=0.9。旧估计V̂(s₁)=1；实际下一动作的Q̂=1，另一个动作的Q̂=3。MC要等看到r₁=2；另外三种可以先用旧估计更新。"),
        table(["方法","在s₀使用的目标y₀","未来来自哪里"],[
          ["MC","−1+0.9×2=0.8","实际观察到的全部后续reward"],
          ["TD(0)","−1+0.9×1=−0.1","旧V̂(s₁)"],
          ["SARSA","−1+0.9×1=−0.1","实际下一动作的旧Q̂"],
          ["Q-learning","−1+0.9×3=1.7","后继最大的旧Q̂"],
        ]),
        prose("这些是训练目标；自举目标会随着估计改进而变化。SARSA与Q-learning在实际下一动作恰好取最大Q时，目标相同；探索选到其他动作时，目标可能不同。")),
      proof("构造目标的条件与收敛条件分开看","7 · 有了更新公式，还需要什么？",
        prose("前面的假设说明目标怎样构造。要保证估计收敛，还需要覆盖、步长和策略条件。下面列平稳MDP、有限表格、有界reward、0≤γ<1下的标准条件；有限时域把剩余时间加入状态。"),
        equation("\\sum_{n=1}^{\\infty}\\eta_n=\\infty,\\qquad\\sum_{n=1}^{\\infty}\\eta_n^2<\\infty",
          "n按每个状态或状态动作自身的更新次数计数。持续学习，但逐渐减小噪声；ηₙ=1/n满足这两条。"),
        table(["方法","额外条件与所学对象"],[
          ["MC评价","固定π、完整且真正结束的回合、相关状态无限访问；用样本平均估计Vπ"],
          ["TD(0)评价","固定π、on-policy采样、相关状态无限访问、上述步长；收敛到Vπ"],
          ["SARSA控制","无限探索且极限贪心（GLIE），再加上述步长，可收敛到Q*"],
          ["Q-learning控制","状态动作无限访问、上述步长；行为可以持续探索，仍可收敛到Q*"],
        ]),
        prose("固定ε>0的SARSA持续评价带探索的策略，不能据此保证Q*。反复回放同一条日志不会产生新环境样本，不能直接套用上述采样保证；神经函数近似需另外分析。",
          "真终止时m=0，目标只有本步r，末端reward计入这次r；外部截断m=1，使用reset前末状态的价值，SARSA在该状态按π采下一动作来补尾。截断时补尾属于自举，不能当作完整MC return。",
          "第9章γ=1的停车任务有有限时域与末端边界，按有限时域分析。")),
      reading("Sutton & Barto · 第5–6章：MC、TD、SARSA与Q-learning","https://www.andrew.cmu.edu/course/10-703/textbook/BartoSutton.pdf"),
      bookReading("§1.1.2–1.1.3：两类Bellman关系",5)),
    chapterFooter("02","数据权限决定能采哪些样本，采样目标把观测到的reward与后续价值连接起来。"));
  return()=>{};
}
export function approximation(root){
  root.append(chapterHeader("03"),
    topic("03","features",
      prose("连续状态难以逐项存表；函数近似共享参数，既能泛化，也会传播拟合误差。",
        "真值V(x)=−x²，仅有x=−1、0、1三个标签；特征(1,x)的最小二乘解为−2/3，加入x²可精确表达真值。"),
      featureLab(),
      equation("\\hat V_w(s)=w^\\top\\phi(s),\\quad\\phi(p,v)=(p^2,2pv,v^2),\\qquad \\hat V=w_1p^2+2w_2pv+w_3v^2",
        "V对特征线性，对状态二次；第9章LQR的权重为(−P₁₁,−P₁₂,−P₂₂)。"),
      prose("另一函数−x²−10·max(|x|−1,0)²与−x²在三个训练点相同，x=2时却分别为−14、−4；零训练误差无法确定未见区域的V。")),
    topic("03","closure",
      table(["假设","定义","要点"],[
        ["最优价值realizability","Q*∈F","能表达最优Q*"],
        ["所有策略realizability","对每个π，Qπ∈F","能表达每个策略的Qπ"],
        ["最优Bellman completeness","对每个f∈F，Tf∈F","每个最优备份仍在F中"],
        ["策略评价completeness","对每个f∈F，Tπf∈F","固定π的每个评价备份仍在F中"],
      ]),
      equation("(Tf)(s,a)=\\mathbb E[r+\\gamma\\max_{a'}f(s',a')\\mid s,a],\\qquad Tf\\in\\mathcal F\\ \\text{for every }f\\in\\mathcal F",
        "闭包要求所有候选f的备份可表达；有限时域使用逐阶段函数类与Tₕ。"),
      prose("能表示Q*只保证最终答案可表达；Bellman completeness要求每轮备份都留在函数类内。")),
    topic("03","offline",
      equation("y_i^{(k)}=r_i+\\gamma m_i\\max_{a'}Q_{k-1}(s_i',a'),\\qquad Q_k\\in\\arg\\min_{f\\in\\mathcal F}\\sum_i(f(s_i,a_i)-y_i^{(k)})^2",
        "FQI固定旧Q的整批目标，再回归新Q；目标停止梯度，连续动作max单独求解。"),
      prose("日志只有|u|≤1的轻推力，两个执行器在此完全相同；|u|>1时，一个正常加速，另一个饱和。相同日志无法区分这两种后果。",
        "离线学习同时需要覆盖目标策略的访问分布，并控制Bellman近似与估计误差。"),
      equation("d^\\pi(s,a)\\le C\\nu(s,a)",
        "占用密度比要有界：新策略访问的区域须有数据支持；缺失支持时没有有限C。"),
      optional("实践连接：DQN、Double DQN与目标网络",
        prose("DQN用神经Q、离散动作和replay；持续交互时属于online。目标网络缓和目标变化，Double DQN分开选动作与评价，离线覆盖仍需检查。"),
        equation("y=r+\\gamma m Q_{\\bar\\theta}(s',\\arg\\max_a Q_\\theta(s',a))",
          "在线网络选动作，目标网络评价；replay改变采样，Huber改变损失，梯度裁剪限制梯度范数，reward裁剪改变任务。"))),
    topic("03","stitching",
      prose("A把小车带到(p=1,v=−0.5)，B从同一状态开始并停稳；用B的后续V评价A，再选择A→B，就是stitching：复用兼容片段的已有转移。",
        "若B从(p=1,v=+0.5)开始，所需刹车与后继不同，位置相同也不能拼接；近邻状态的误差需由模型、表示或局部控制处理。"),
      equation("G_{A\\to B}=\\sum_{t=0}^{k-1}\\gamma^tr_t^A+\\gamma^kG_B",
        "A有两步零reward，B有两步[0,1]，γ=0.9：return=γ²×γ=0.729；连接须真实可行，完整状态与任务均须匹配。"),
      table(["操作","得到什么","所需条件"],[
        ["复用B的后续V","已有连接的长期估计","使用已有转移"],
        ["规划A→B","兼容片段的组合","连接状态物理匹配"],
        ["补采缺失连接","新的真实数据","保证仍限于已采区域"],
      ]),
      bookReading("第3–4章：函数近似与覆盖",35)),
    chapterFooter("03","表示决定能拟合什么，覆盖决定数据支持哪里；stitching复用物理兼容的连接。"));
  return()=>{};
}
export function exploration(root){
  root.append(chapterHeader("04"),
    topic("04","bandit",
      prose("每次重置物体，试一种夹持力度，以成功率和能耗定义单步reward，这就是bandit。",
        "A试100次、均值0.6，B只试1次、均值0.5；UCB用均值加不确定性，避免过早放弃B。"),
      equation("a_t\\in\\arg\\max_a\\left[\\hat\\mu_a+c\\sqrt{\\frac{\\log t}{N_a}}\\right]",
        "未试动作先试；c取决于噪声与置信条件，UCB是乐观估计。"),
      table(["动作","样本数","样本均值","不确定性"],[["A",100,0.6,"较小"],["B",1,0.5,"较大"]]),
      optional("线性bandit与理论界",
        prose("线性bandit通过动作特征共享reward信息，用线性回归与椭圆置信集构造LinUCB；regret分析见第5章。"),bookReading("第5章",63))),
    topic("04","strategic",
      prose("抓取经过“对准→接触→夹紧→抬起”；每步3个候选、仅1个能继续，独立均匀随机完成四步的概率为1/81，末端reward很难被发现。",
        "策略性探索先到达能获得信息的状态，再测试未知动作；目标课程可用中间可达目标组织长任务。Online探索沿轨迹采样，受可达性限制。"),
      equation("Q_h^{\\mathrm{opt}}(s,a)=\\hat r_h(s,a)+\\hat P_hV_{h+1}^{\\mathrm{opt}}(s,a)+b_h(s,a)",
        "乐观备份加入统计置信bonus，并常截断到合法值域；bonus须满足相应置信条件。"),
      prose("动作噪声改变行为，熵项改变目标，目标课程改变任务分布，模型置信探索引导访问；最终评估使用原任务reward与可执行动作范围。")),
    topic("04","structure",
      equation("P_h(s'\\mid s,a)=\\phi(s,a)^\\top\\mu_h(s'),\\qquad r_h(s,a)=\\phi(s,a)^\\top\\theta_h",
        "第7章假设转移核特征线性、reward已知且有界；上式是reward也线性的加强版本，概率核须合法并满足有界与归一化条件。"),
      prose("Linear MDP用特征组合整个后继分布，例如两种落点分布的混合；x′=Ax+Bu描述物理状态的线性变化，两者是不同假设。",
        "Bellman rank描述采样策略与候选价值函数的平均Bellman残差是否低维分解，依赖函数类和访问分布；条件须覆盖理论要求的全部候选，而非几个实验矩阵。"),
      optional("选读：原书第7–8章的算法与保证",
        prose("Lin-UCBVI、Bellman-rank消除算法与PAC/regret界依赖各自的访问和结构假设；集中、椭圆势与下界证明见第7–8章。"),
        bookReading("Linear MDP / Bellman rank",87))),
    chapterFooter("04","探索既要试未知动作，也要到达能获得信息的状态；结构假设支持跨状态泛化。"));
  return()=>{};
}
