import {h} from "../ui/dom.js";
import {tex} from "../ui/math.js";
import {chapterHeader,chapterFooter,topic,prose,equation,proof,table,optional,bookReading,reading} from "./shell.js";
import {stateLab,bellmanLab,featureLab} from "./labs.js";
export function mdp(root){
  root.append(chapterHeader("01"),
    topic("01","task",
      prose("小车从p=2 m出发，在p=0附近停稳；每0.5秒选择连续推力u，既要接近目标，也要及时刹车。",
        "同位置、同推力下，v=+1与v=−1产生不同后继，因此状态需包含速度。"),
      stateLab(),
      equation("s_t=(p_t,v_t),\\quad u_t\\in\\mathbb R,\\quad s_{t+1}\\sim P(\\cdot\\mid s_t,u_t),\\quad u_t\\sim\\pi(\\cdot\\mid s_t)",
        "π选择动作，P给出下一状态的分布。"),
      table(["MDP对象","符号与公式","小车中的含义"],[
        [h("span",{},"状态 ",tex("\\mathcal S")),tex("s_t=(p_t,v_t)\\in\\mathcal S=\\mathbb R^2"),"位置与速度"],
        [h("span",{},"动作 ",tex("\\mathcal A")),tex("a_t=u_t\\in\\mathcal A=\\mathbb R"),"一个采样周期内的推力"],
        [h("span",{},"转移 ",tex("P")),tex("P(\\cdot\\mid s_t,u_t)=\\delta_{f(s_t,u_t)}"),"下一状态确定为f(sₜ,uₜ)"],
        [h("span",{},"reward ",tex("r")),tex("r(s_t,u_t)=-(p_t-g)^2-0.2v_t^2-0.5u_t^2"),"接近目标、停稳、少用力；g=0"],
        [h("span",{},"初始分布 ",tex("\\rho_0")),tex("s_0\\sim\\rho_0,\\quad\\rho_0=\\delta_{(2,0)}"),"默认从2 m静止出发"],
      ]),
      equation("\\boxed{\\begin{aligned}p_{t+1}&=p_t+v_t\\Delta t+\\frac{u_t}{2m}\\Delta t^2\\\\v_{t+1}&=v_t+\\frac{u_t}{m}\\Delta t\\end{aligned}}\\qquad s_{t+1}=f(s_t,u_t)",
        "牛顿第二定律＋匀加速运动：m=1 kg、Δt=0.5 s，每步推力恒定，忽略摩擦。"),
      prose(h("span",{},tex("\\delta_x"),"表示状态确定为x；有限时域再把剩余步数H−t加入状态。"),
        "Markov性：给定当前状态和动作，下一状态与更早的历史无关。")),
    topic("01","values",
      prose("持续向左推可能高速穿过目标；速度反馈让小车提前反向刹车，整条轨迹的return决定哪种策略更好。",
        "令e为位置误差；例如每步r=−e²−0.2v²−0.5u²，末端r_H=−20e_H²−10v_H²，误差、速度和推力越大，reward越低。"),
      equation("G_t=\\sum_{k\\ge0}\\gamma^kr_{t+k},\\qquad J(\\pi)=\\mathbb E_{s_0\\sim\\rho_0,\\pi}G_0,\\qquad \\pi^*\\in\\arg\\max_\\pi J(\\pi)",
        "G是轨迹return，J是从ρ₀出发的期望return；γ决定远期reward的权重。"),
      equation("V^\\pi(s)=\\mathbb E_\\pi[G_t\\mid s_t=s],\\qquad Q^\\pi(s,a)=\\mathbb E_\\pi[G_t\\mid s_t=s,a_t=a]",
        "V从当前状态按π行动，Q先指定a再按π行动；两者都是期望return。"),
      prose("有限时域记Vₜ：还剩1步与6步可能需要不同推力；无限折扣用γ<1，第9章有限时域用γ=1并计入末端reward。")),
    topic("01","bellman",
      prose("设γ=1、e=2，后继e′=e+u，一步reward为−e²−0.5u²，后续V(e′)=−Pe′²；P=4时，u=0、−2、−1的return分别为−20、−6、−8.5。"),
      bellmanLab(),
      proof("递推定义","Bellman：一步reward＋后续V",
        equation("G_t=r_t+\\gamma G_{t+1},\\quad Q^\\pi(s,a)=\\mathbb E[r+\\gamma V^\\pi(s')\\mid s,a],\\quad V^\\pi(s)=\\mathbb E_{a\\sim\\pi}Q^\\pi(s,a)",
          "Q对环境后继取期望，V再对策略动作取期望。"),
        equation("Q^*(s,a)=\\mathbb E[r+\\gamma V^*(s')\\mid s,a],\\qquad V^*(s)=\\max_aQ^*(s,a)",
          "最优动作最大化Q*；连续动作若最优点未达到，max应写为sup。"),
        equation("V(e)=\\max_u\\{-e^2-0.5u^2-P(e+u)^2\\},\\qquad u^*=-\\frac{P}{0.5+P}e",
          "P=4时，唯一最优推力u*=−1.777778，V(2)=−5.777778；连续动作需优化整个区间。"))),
    topic("01","planning",
      table(["方法","固定或读取什么","更新什么"],[
        ["策略评价","固定π","计算Vπ或Qπ"],
        ["策略改进","读取Qπ","选取最大Qπ的动作"],
        ["策略迭代","循环评价与改进","更新策略，区别于梯度更新"],
        ["价值迭代","读取旧V的最优后续","V←TV，再提取贪心策略"],
      ]),
      equation("(TV)(s)=\\max_a\\mathbb E[r+\\gamma V(s')\\mid s,a],\\qquad \\|TV-TU\\|_\\infty\\le\\gamma\\|V-U\\|_\\infty",
        "有限表格、有界reward、γ<1时，收缩保证唯一最优固定点；无界二次reward需另行分析。"),
      equation("V_t^*(s)=\\max_a\\mathbb E[r_t+V_{t+1}^*(s')\\mid s,a],\\qquad V_H(s)=r_H(s)",
        "有限时域从末端reward倒推；第9章Riccati在二次价值函数中完成这一递推。"),
      optional("选读：线性规划、复杂度与性能差",
        prose("线性规划与算法复杂度见§1.3–1.5；性能差恒等式用于第7章策略更新。"),bookReading("§1.3–1.5",11)),
      bookReading("第1章",3)),
    chapterFooter("01","已知模型时，Bellman递推把整条未来的期望return转化为逐步规划。"));
  return()=>{};
}
export function data(root){
  root.append(chapterHeader("02"),
    topic("02","access",
      prose("数据接口决定怎样估计Bellman期望：查询任意合法状态动作、读取固定日志，或沿轨迹交互。"),
      table(["接口","允许的操作","小车例子"],[
        ["Generative model / 采样oracle","指定合法(s,a)，独立采样后继","重置到同一(p,v)，重复施加推力；有限时域可指定阶段"],
        ["Offline","只读固定数据集D","用低速驾驶日志训练，不能补采高推力结果"],
        ["Online","执行轨迹，取得新数据","沿策略开车；访问受策略与可达性限制"],
      ]),
      prose("Generative model允许独立查询任意合法(s,a)的后继；真机通常只能沿轨迹采样。使用replay仍属online，只有固定日志才是offline。")),
    topic("02","statistics",
      equation("\\widehat{PV}(s,a)=\\frac1n\\sum_{i=1}^nV(s_i'),\\qquad \\operatorname{Var}(\\widehat{PV})=\\frac{\\operatorname{Var}(V(S'))}{n}",
        "固定V，在同一(s,a)独立采样，标准差随1/√n下降。"),
      prose("同一制动力下，后继V以各1/2概率为0或2，均值1、方差1；平均4个独立后继的方差为1/4，100个为1/100。样本精度与状态动作覆盖是两件事。",
        "若真实与估计算子在相关有界函数上均相差至多ε，且均为γ收缩（γ<1），固定点误差满足下式。"),
      equation("\\|\\hat V^*-V^*\\|_\\infty\\le\\frac{\\epsilon}{1-\\gamma}",
        "γ=0.9、0.99时分别放大10、100倍；样本复杂度还取决于reward界、覆盖、置信度与采样接口。"),
      optional("选读：minimax样本复杂度",
        prose("第2章给出方差分析与近最优样本数量；结论适用于其表格、采样oracle与有界reward假设。"),bookReading("第2章",21))),
    topic("02","updates",
      prose("MC用完整回合return作目标；TD用一步reward加估计的后继V，自举尚未观察的未来。"),
      equation("V(s_t)\\leftarrow V(s_t)+\\eta[G_t-V(s_t)]\\quad(\\mathrm{MC}),\\qquad V(s_t)\\leftarrow V(s_t)+\\eta\\delta_t,\\quad\\delta_t=r_t+\\gamma m_tV(s_{t+1})-V(s_t)",
        "真终止不接后继V；截断接reset前末状态的V。末端reward计入最后一步。"),
      equation("Q(s_t,a_t)\\leftarrow Q(s_t,a_t)+\\eta[r_t+\\gamma m_tQ(s_{t+1},a_{t+1})-Q(s_t,a_t)]\\quad(\\mathrm{SARSA})",
        "下一动作来自行为策略，目标包含其探索选择。"),
      equation("Q(s_t,a_t)\\leftarrow Q(s_t,a_t)+\\eta[r_t+\\gamma m_t\\max_{a'}Q(s_{t+1},a')-Q(s_t,a_t)]\\quad(\\text{Q-learning})",
        "目标用贪心后续，行为可探索；连续动作max需单独优化。"),
      table(["目标","未来来源","小算例"],[
        ["MC","回合中观察的全部未来","r=[0,1]、γ=0.9：G₀=0.9"],
        ["TD","真实一步＋旧V","r=0、旧V=0.7、γ=0.9：目标0.63"],
        ["SARSA","实际下一动作的旧Q","r=0、探索动作Q=−2、γ=0.9：目标−1.8"],
        ["Q-learning","后继最大的旧Q","r=0、最大Q=3、γ=0.9：目标2.7"],
      ]),
      prose("表格更新的收敛依赖覆盖、步长、任务与策略条件；神经函数近似需另行分析。"),
      reading("Sutton & Barto · Monte Carlo与TD采样补充","https://www.andrew.cmu.edu/course/10-703/textbook/BartoSutton.pdf"),
      bookReading("第2章：数据模型与统计",21)),
    chapterFooter("02","数据权限决定能采哪些样本，采样目标把观测到的reward与后续价值连接起来。"));
  return()=>{};
}
export function approximation(root){
  root.append(chapterHeader("03"),
    topic("03","features",
      prose("连续状态难以逐项存表；函数近似共享参数，既能泛化，也会传播拟合误差。",
        "真值V(x)=−x²，仅有x=−1、0、1三个标签；特征(1,x)的最小二乘解为−2/3，加入x²可精确表达真值。"),
      featureLab(),
      equation("\\hat V_w(s)=w^\\top\\phi(s),\\quad\\phi(p,v)=(p^2,2pv,v^2),\\qquad \\hat V=w_1p^2+2w_2pv+w_3v^2",
        "V对特征线性，对状态二次；第9章LQR的权重为(−P₁₁,−P₁₂,−P₂₂)。"),
      prose("另一函数−x²−10·max(|x|−1,0)²与−x²在三个训练点相同，x=2时却分别为−14、−4；零训练误差无法确定未见区域的V。")),
    topic("03","closure",
      table(["假设","定义","要点"],[
        ["最优价值realizability","Q*∈F","能表达最优Q*"],
        ["所有策略realizability","对每个π，Qπ∈F","能表达每个策略的Qπ"],
        ["最优Bellman completeness","对每个f∈F，Tf∈F","每个最优备份仍在F中"],
        ["策略评价completeness","对每个f∈F，Tπf∈F","固定π的每个评价备份仍在F中"],
      ]),
      equation("(Tf)(s,a)=\\mathbb E[r+\\gamma\\max_{a'}f(s',a')\\mid s,a],\\qquad Tf\\in\\mathcal F\\ \\text{for every }f\\in\\mathcal F",
        "闭包要求所有候选f的备份可表达；有限时域使用逐阶段函数类与Tₕ。"),
      prose("能表示Q*只保证最终答案可表达；Bellman completeness要求每轮备份都留在函数类内。")),
    topic("03","offline",
      equation("y_i^{(k)}=r_i+\\gamma m_i\\max_{a'}Q_{k-1}(s_i',a'),\\qquad Q_k\\in\\arg\\min_{f\\in\\mathcal F}\\sum_i(f(s_i,a_i)-y_i^{(k)})^2",
        "FQI固定旧Q的整批目标，再回归新Q；目标停止梯度，连续动作max单独求解。"),
      prose("日志只有|u|≤1的轻推力，两个执行器在此完全相同；|u|>1时，一个正常加速，另一个饱和。相同日志无法区分这两种后果。",
        "离线学习同时需要覆盖目标策略的访问分布，并控制Bellman近似与估计误差。"),
      equation("d^\\pi(s,a)\\le C\\nu(s,a)",
        "占用密度比要有界：新策略访问的区域须有数据支持；缺失支持时没有有限C。"),
      optional("实践连接：DQN、Double DQN与目标网络",
        prose("DQN用神经Q、离散动作和replay；持续交互时属于online。目标网络缓和目标变化，Double DQN分开选动作与评价，离线覆盖仍需检查。"),
        equation("y=r+\\gamma m Q_{\\bar\\theta}(s',\\arg\\max_a Q_\\theta(s',a))",
          "在线网络选动作，目标网络评价；replay改变采样，Huber改变损失，梯度裁剪限制梯度范数，reward裁剪改变任务。"))),
    topic("03","stitching",
      prose("A把小车带到(p=1,v=−0.5)，B从同一状态开始并停稳；用B的后续V评价A，再选择A→B，就是stitching：复用兼容片段的已有转移。",
        "若B从(p=1,v=+0.5)开始，所需刹车与后继不同，位置相同也不能拼接；近邻状态的误差需由模型、表示或局部控制处理。"),
      equation("G_{A\\to B}=\\sum_{t=0}^{k-1}\\gamma^tr_t^A+\\gamma^kG_B",
        "A有两步零reward，B有两步[0,1]，γ=0.9：return=γ²×γ=0.729；连接须真实可行，完整状态与任务均须匹配。"),
      table(["操作","得到什么","所需条件"],[
        ["复用B的后续V","已有连接的长期估计","使用已有转移"],
        ["规划A→B","兼容片段的组合","连接状态物理匹配"],
        ["补采缺失连接","新的真实数据","保证仍限于已采区域"],
      ]),
      bookReading("第3–4章：函数近似与覆盖",35)),
    chapterFooter("03","表示决定能拟合什么，覆盖决定数据支持哪里；stitching复用物理兼容的连接。"));
  return()=>{};
}
export function exploration(root){
  root.append(chapterHeader("04"),
    topic("04","bandit",
      prose("每次重置物体，试一种夹持力度，以成功率和能耗定义单步reward，这就是bandit。",
        "A试100次、均值0.6，B只试1次、均值0.5；UCB用均值加不确定性，避免过早放弃B。"),
      equation("a_t\\in\\arg\\max_a\\left[\\hat\\mu_a+c\\sqrt{\\frac{\\log t}{N_a}}\\right]",
        "未试动作先试；c取决于噪声与置信条件，UCB是乐观估计。"),
      table(["动作","样本数","样本均值","不确定性"],[["A",100,0.6,"较小"],["B",1,0.5,"较大"]]),
      optional("线性bandit与理论界",
        prose("线性bandit通过动作特征共享reward信息，用线性回归与椭圆置信集构造LinUCB；regret分析见第5章。"),bookReading("第5章",63))),
    topic("04","strategic",
      prose("抓取经过“对准→接触→夹紧→抬起”；每步3个候选、仅1个能继续，独立均匀随机完成四步的概率为1/81，末端reward很难被发现。",
        "策略性探索先到达能获得信息的状态，再测试未知动作；目标课程可用中间可达目标组织长任务。Online探索沿轨迹采样，受可达性限制。"),
      equation("Q_h^{\\mathrm{opt}}(s,a)=\\hat r_h(s,a)+\\hat P_hV_{h+1}^{\\mathrm{opt}}(s,a)+b_h(s,a)",
        "乐观备份加入统计置信bonus，并常截断到合法值域；bonus须满足相应置信条件。"),
      prose("动作噪声改变行为，熵项改变目标，目标课程改变任务分布，模型置信探索引导访问；最终评估使用原任务reward与可执行动作范围。")),
    topic("04","structure",
      equation("P_h(s'\\mid s,a)=\\phi(s,a)^\\top\\mu_h(s'),\\qquad r_h(s,a)=\\phi(s,a)^\\top\\theta_h",
        "第7章假设转移核特征线性、reward已知且有界；上式是reward也线性的加强版本，概率核须合法并满足有界与归一化条件。"),
      prose("Linear MDP用特征组合整个后继分布，例如两种落点分布的混合；x′=Ax+Bu描述物理状态的线性变化，两者是不同假设。",
        "Bellman rank描述采样策略与候选价值函数的平均Bellman残差是否低维分解，依赖函数类和访问分布；条件须覆盖理论要求的全部候选，而非几个实验矩阵。"),
      optional("选读：原书第7–8章的算法与保证",
        prose("Lin-UCBVI、Bellman-rank消除算法与PAC/regret界依赖各自的访问和结构假设；集中、椭圆势与下界证明见第7–8章。"),
        bookReading("Linear MDP / Bellman rank",87))),
    chapterFooter("04","探索既要试未知动作，也要到达能获得信息的状态；结构假设支持跨状态泛化。"));
  return()=>{};
}
