import {h} from "../ui/dom.js";
import {chapterHeader,chapterFooter,topic,prose,equation,proof,table,optional,bookReading,reading} from "./shell.js";
import {gaussianLab,baselineLab,gaeLab,geometryLab,surrogateLab,ppoLab,entropyLab} from "./labs.js";
const PG="https://spinningup.openai.com/en/latest/spinningup/rl_intro3.html";
const GAE="https://arxiv.org/pdf/1506.02438";
const TRPO="https://arxiv.org/pdf/1502.05477";
const PPO="https://arxiv.org/pdf/1707.06347";
export function gradient(root){
  root.append(chapterHeader("05"),
    topic("05","gaussian",
      prose("连续Gaussian策略让网络输出均值μθ(s)与标准差σθ(s)>0，再采样推力；μ决定平均推力，σ控制随机性。",
        "固定状态和σ，只更新μ：样本u=−1、优势+2会增加附近密度，优势−2则减少；完整训练按当前策略采样轨迹。"),
      gaussianLab(),
      equation("u\\sim\\mathcal N(\\mu_\\theta(s),\\sigma^2),\\quad\\log\\pi(u\\mid s)=-\\frac{(u-\\mu)^2}{2\\sigma^2}-\\log\\sigma-\\frac12\\log(2\\pi),\\quad\\partial_\\mu\\log\\pi=\\frac{u-\\mu}{\\sigma^2}",
        "密度可大于1，单个动作概率仍为0；推力有界时用第10章的变换密度。"),
      prose("长期优势评价动作；均值更新会改变后续状态访问，因此要从整条轨迹推导梯度。")),
    topic("05","derivation",
      proof("任务与正则条件","1 · θ改变轨迹分布",
        prose("初始分布、转移与reward不依赖θ；策略可微、支持固定，可交换积分与求导。取有限T，终止后补零reward。"),
        equation("p_\\theta(\\tau)=\\rho_0(s_0)\\prod_{t=0}^{T-1}\\pi_\\theta(a_t\\mid s_t)P(s_{t+1},r_t\\mid s_t,a_t),\\qquad J_\\gamma=\\int p_\\theta(\\tau)\\sum_t\\gamma^tr_t\\,d\\tau",
          "目标最大化Jγ；小车reward惩罚误差、速度和推力的平方，并含末端reward。")),
      proof("对数导数恒等式","2 · 导数变成采样期望",
        equation("\\nabla p_\\theta=p_\\theta\\nabla\\log p_\\theta,\\qquad\\nabla\\log p_\\theta(\\tau)=\\sum_t\\nabla\\log\\pi_\\theta(a_t\\mid s_t)",
          "log把乘积变成和；环境不依赖θ，其导数为0，否则须补额外项。"),
        equation("\\nabla J_\\gamma=\\mathbb E_{\\tau\\sim p_\\theta}\\left[\\left(\\sum_k\\gamma^kr_k\\right)\\sum_t\\nabla\\log\\pi_\\theta(a_t\\mid s_t)\\right]",
          "REINFORCE用当前策略轨迹估计梯度，无须对动力学求导。")),
      proof("条件期望恒等式","3 · 删除过去reward",
        equation("z_t=\\nabla\\log\\pi_\\theta(a_t\\mid s_t),\\quad\\mathbb E[z_t\\mid H_t]=\\int\\pi_\\theta(a\\mid s_t)\\nabla\\log\\pi_\\theta(a\\mid s_t)\\,da=\\nabla\\int\\pi_\\theta(a\\mid s_t)\\,da=0",
          "Hₜ是动作前历史：过去reward已知，乘score的条件期望为0；积分须满足上述条件。"),
        equation("\\boxed{\\nabla J_\\gamma=\\mathbb E\\left[\\sum_t\\gamma^tG_t\\nabla\\log\\pi_\\theta(a_t\\mid s_t)\\right]}",
          "Gₜ从t重新折扣，初始折扣目标需外乘γᵗ；有限时域γ=1时该因子为1。")),
      proof("条件期望与占用","4 · 得到PG定理",
        equation("\\nabla J_\\gamma=\\frac1{1-\\gamma}\\mathbb E_{s\\sim d_\\gamma^\\pi,a\\sim\\pi}[Q^\\pi(s,a)\\nabla\\log\\pi_\\theta(a\\mid s)]",
          "γ<1、值有界；占用测度dγ(B)=(1−γ)ΣγᵗPr(Sₜ∈B)，访问变化已计入梯度。")),
      reading("对数导数与因果性",PG)),
    topic("05","baseline",
      equation("\\mathbb E_{a\\sim\\pi}[b(s)\\nabla\\log\\pi(a\\mid s)]=b(s)\\nabla\\int\\pi(a\\mid s)\\,da=0",
        "给定状态，baseline与当前动作无关时梯度均值不变；动作相关基线通常需修正。"),
      equation("A^\\pi(s,a)=Q^\\pi(s,a)-V^\\pi(s),\\qquad g=(G-b(s))\\nabla\\log\\pi(a\\mid s)",
        "baseline改变波动；常用Vπ未必使方差最低。"),
      baselineLab(),
      prose("单步u∼N(μ,1)、r=−(u+1)²，J=−[(μ+1)²+1]；μ=0时梯度−2。b=0、−2、−4、+2的方差依次为30、18、14、50。",
        "单个梯度项的最低方差基线b*=E[∥score∥²G]/E[∥score∥²]；整条轨迹还受跨时刻相关性与critic误差影响。")),
    topic("05","actor-critic",
      equation("\\delta_t=r_t+\\gamma m_tV_{old}(s_{t+1})-V_{old}(s_t),\\qquad\\hat A_t=\\delta_t+\\gamma\\lambda c_t\\hat A_{t+1}",
        "GAE反向递推：mₜ控制bootstrap，cₜ控制是否连接下一条同轨迹δ。"),
      gaeLab(),
      table(["边界","m：bootstrap","c：接下一条δ"],[["正常继续",1,1],["真正终止",0,0],["外部时间截断",1,0],["rollout切段",1,0]]),
      prose("截断用reset前末观察bootstrap；有限任务到期是真终止，状态须含剩余时间。λ=0给一步TD，完整终止轨迹λ=1给G−V；中间λ折中采样波动与critic误差。",
        "actor用detach优势加权log-density，critic拟合固定目标Vold+Â；共享网络须检查梯度耦合。"),
      equation("\\theta\\leftarrow\\theta+\\eta_\\pi\\gamma^t\\hat A_t\\nabla_\\theta\\log\\pi_\\theta(a_t\\mid s_t),\\qquad L_V=\\tfrac12(V_\\phi(s_t)-\\operatorname{stopgrad}(V_{old}(s_t)+\\hat A_t))^2",
        "actor沿优势方向更新，critic拟合固定的return目标。"),
      reading("GAE §2–3",GAE),bookReading("第9章",111)),
    chapterFooter("05","轨迹score给PG，因果性删过去reward，baseline改波动，GAE估计优势。"));
  return()=>{};
}
export function natural(root){
  root.append(chapterHeader("06"),
    topic("06","optimality",
      prose("reward为0和1的两动作中，softmax选好动作的概率p=0.001，则J=0.001、logit梯度0.000999：小梯度仍可对应差策略。"),
      equation("J(\\theta)=p,\\quad p=\\sigma(\\theta),\\quad\\frac{dJ}{d\\theta}=p(1-p)",
        "好动作或关键状态很少被访问时，普通PG可能改善缓慢。"),
      table(["结论","含义与条件"],[
        ["Stationary","给定参数化中梯度为0"],
        ["Global optimal","指定任务与策略集合内return最高"],
        ["表格softmax","需要准确梯度、覆盖、合适步长"],
        ["神经Gaussian","非凸、近似critic、有限数据；全局保证须另证"],
      ]),
      prose("原书第10章分析softmax、覆盖与log barrier；机器人网络、动作尺度和数据分布须另查条件。")),
    topic("06","geometry",
      prose("Gaussian均值同样改0.2 N，σ=1 N时KL=0.02，σ=0.1 N时KL=2：相同步长的行为变化相差100倍。"),
      geometryLab(),
      equation("D_{KL}(\\mathcal N(\\mu,\\sigma^2)\\Vert\\mathcal N(\\mu+\\Delta\\mu,\\sigma^2))=\\frac{(\\Delta\\mu)^2}{2\\sigma^2},\\qquad F_{\\mu\\mu}=\\frac1{\\sigma^2}",
        "固定方差时精确；一般KL仅在局部近似为Fisher二次型。"),
      equation("F=\\mathbb E[zz^\\top],\\quad z=\\nabla\\log\\pi,\\qquad\\max_\\Delta g^\\top\\Delta\\ \\text{s.t.}\\ \\tfrac12\\Delta^\\top F\\Delta\\le\\kappa",
        "F与g按当前策略/占用计算；目标线性化，KL用局部二次近似。"),
      equation("\\Delta=\\sqrt{\\frac{2\\kappa}{g^\\top F^{-1}g}}F^{-1}g",
        "需F正定、g≠0、κ>0；奇异F可加damping，更新后检查真实KL。")),
    topic("06","compatible",
      equation("\\hat A_w(s,a)=w^\\top z(s,a),\\qquad\\min_w\\mathbb E[(w^\\top z-A)^2]\\ \\Longrightarrow\\ Fw=\\mathbb E[zA]",
        "score特征的回归给Fisher方向；期望分布与PG权重须一致，折扣常数可并入步长。"),
      prose("兼容近似让优势特征匹配actor的score；普通critic、有限样本或分布变化会引入额外误差。",
        "固定σ的一维均值策略有F=1/σ²，自然方向为σ²g；固定KL预算允许的均值步长与σ成正比。"),
      optional("选读：NPG/Q-NPG的速率与误差",
        prose("原书第11章分析近似误差与覆盖；速率结论须匹配函数类和数据条件。"),bookReading("第10–11章",119))),
    chapterFooter("06","覆盖影响梯度，Fisher衡量行为变化，兼容回归给出自然梯度方向。"));
  return()=>{};
}
export function conservative(root){
  root.append(chapterHeader("07"),
    topic("07","surrogate",
      proof("望远镜求和","真实性能差",
        equation("J(\\pi)-J(\\pi_{old})=\\frac1{1-\\gamma}\\mathbb E_{s\\sim d_\\gamma^\\pi,a\\sim\\pi}[A^{old}(s,a)]",
          "γ<1、价值有界；沿新策略累计r+γVold(s′)−Vold(s)，旧价值中间项消去，访问分布仍是新策略的。")),
      proof("固定旧状态分布","定义surrogate近似",
        equation("L_{old}(\\pi)=J(\\pi_{old})+\\frac1{1-\\gamma}\\mathbb E_{s\\sim d_\\gamma^{old},a\\sim\\pi}[A^{old}(s,a)]",
          "L与J仅在旧参数处保证同值、同梯度。"),
        surrogateLab(),
        prose("p=0.9时，q=0.1得J=1.044、L=1.62，q=0.9得J=1.396、L=0.82；L固定旧访问概率0.5，因此可在J两侧。")),
      equation("\\mathbb E_{a\\sim\\pi_\\theta(\\cdot\\mid s)}A^{old}(s,a)=\\mathbb E_{a\\sim\\pi_{old}(\\cdot\\mid s)}\\left[\\frac{\\pi_\\theta(a\\mid s)}{\\pi_{old}(a\\mid s)}A^{old}(s,a)\\right]",
        "旧策略覆盖新策略支持时，固定s的动作换测度精确；连续动作用密度比，不改旧状态占用。")),
    topic("07","trust-region",
      prose("CPI混合旧策略与候选策略；TRPO用KL信赖域更新，局部线性目标与二次KL近似给出第6章的自然方向。",
        "理论界含最大逐状态变化，常用实现约束旧占用下的平均KL；两者不同。"),
      equation("\\pi_{new}=(1-\\eta)\\pi_{old}+\\eta\\pi_{candidate},\\qquad \\bar D=\\mathbb E_{s\\sim d^{old}}D_{KL}(\\pi_{old}\\Vert\\pi_{new})",
        "混合的是策略分布；参数插值不同。平均KL易采样，却不控制每个状态。"),
      prose("状态权重0.99与0.01、KL分别0与1 nat，平均0.01、最大1：罕见接触状态可剧变；采样均值另有估计误差。"),
      reading("TRPO：性能差与信赖域",TRPO)),
    topic("07","ppo",
      prose("PPO在旧批次上优化clip目标：改善方向越过阈值后进入平台，坏方向仍受惩罚；这是局部目标设计。"),
      equation("w_t(\\theta)=\\exp(\\log\\pi_\\theta(a_t\\mid s_t)-\\log\\pi_{old}(a_t\\mid s_t)),\\quad L^{clip}=\\hat{\\mathbb E}_t\\min(w_t\\hat A_t,\\operatorname{clip}(w_t,1-\\epsilon,1+\\epsilon)\\hat A_t)",
        "w是概率/密度比；actor最大化Lclip，实现中取loss=−Lclip。"),
      ppoLab(),
      equation("\\ell(w,A)=\\begin{cases}A\\min(w,1+\\epsilon),&A\\ge0\\\\A\\max(w,1-\\epsilon),&A<0\\end{cases}",
        "ε=0.2：A=2,w=1.5得2.4；A=−2,w=0.5得−1.6；A=−2,w=1.5仍为−3。"),
      prose("正优势w过小、负优势w过大时仍有梯度。clip逐样本不高于未裁剪项，却不是J的全局下界，也不硬约束ratio或KL；共享参数仍可推动平台区动作。"),
      reading("PPO §3、§5",PPO)),
    topic("07","entropy",
      prose("log是凹函数，Jensen给出“先平均再取log”≥“先取log再平均”。"),
      equation("\\mathbb E\\log X\\le\\log\\mathbb EX\\quad(X>0),\\qquad Z=\\sum_a e^{Q(a)/\\alpha}",
        "此处动作有限、α>0；连续动作改用微分熵。"),
      ...entropyLab(),
      proof("插入π，再用Jensen","得到Q加熵目标",
        equation("\\alpha\\log Z=\\alpha\\log\\mathbb E_{a\\sim\\pi}\\frac{e^{Q(a)/\\alpha}}{\\pi(a)}\\ge\\mathbb E_\\pi Q+\\alpha H(\\pi)",
          "π须覆盖所有动作，零概率可取极限。"),
        equation("\\pi^*(a)=e^{Q(a)/\\alpha}/Z,\\qquad \\alpha\\log Z-(\\mathbb E_\\pi Q+\\alpha H)=\\alpha D_{KL}(\\pi\\Vert\\pi^*)",
          "差距为α×KL，softmax达到上界；熵正则改变目标。")),
      equation("\\alpha\\log\\sum_a e^{Q(a)/\\alpha}=m+\\alpha\\log\\sum_a e^{(Q(a)-m)/\\alpha},\\quad m=\\max_aQ(a)",
        "先减最大值防溢出；Q=(1000,1002)、α=1得1002.126928。"),
      reading("最大熵RL与固定动力学推断","https://arxiv.org/html/1805.00909v3#S3.SS2")),
    topic("07","practice",
      table(["步骤","操作","原因"],[
        ["采集rollout","冻结πold，存旧log-density、V与真实末观察","确定采样策略"],
        ["估计优势","算GAE与critic目标，再detach","固定训练目标"],
        ["多轮minibatch","更新actor/critic，固定旧分母","避免ratio重置为1"],
        ["连续联合动作","各维log-density求和后算ratio","对联合动作算clip"],
        ["标准化与范数裁剪","记录batch范围和步长","中心化可改优势符号，无偏性须另查"],
        ["KL与clip fraction","监测行为变化，必要时停止本批","clip不硬约束KL"],
        ["重采样与评估","采新轨迹，独立评估","检验真实任务表现"],
      ]),
      h("pre",{class:"algorithm-flow"},h("code",{},"旧策略rollout → GAE与return → 冻结旧量\n新log-density → ratio → actor/critic/entropy loss\nminibatch更新、监测KL → 重采样 → 独立评估")),
      optional("选读：保守优化与完整训练",
        prose("原书§12.3讲正交化与逐行归一化；机器人训练流程见第10章。"),bookReading("第12章",141))),
    chapterFooter("07","性能差是恒等式，固定旧占用是近似，动作ratio精确换测度，clip设计局部目标；训练后须实际评估。"));
  return()=>{};
}
