import {h} from "../ui/dom.js";
import {chapterHeader,chapterFooter,topic,prose,equation,proof,table,optional,bookReading,reading} from "./shell.js";
import {gaussianLab,baselineLab,gaeLab,geometryLab,surrogateLab,ppoLab,entropyLab} from "./labs.js";
const PG="https://spinningup.openai.com/en/latest/spinningup/rl_intro3.html";
const GAE="https://arxiv.org/pdf/1506.02438";
const TRPO="https://arxiv.org/pdf/1502.05477";
const PPO="https://arxiv.org/pdf/1707.06347";
export function gradient(root){
  root.append(chapterHeader("05"),
    topic("05","gaussian",
      prose("连续推力有无穷多个可能值，不能为每个值存一格Q。直接令策略网络输出均值μθ(s)和正标准差σθ(s)，再从动作密度中采样。均值代表通常想施加的推力，方差代表此状态下的随机性。",
        "先固定状态和σ，只训练均值。观察到u=−1且优势+2时，增加这个动作附近的密度；若优势−2，则把分布移离它。指定样本只是展示更新方向，完整训练要按当前策略采样轨迹。"),
      gaussianLab(),
      equation("u\\sim\\mathcal N(\\mu_\\theta(s),\\sigma^2),\\quad\\log\\pi(u\\mid s)=-\\frac{(u-\\mu)^2}{2\\sigma^2}-\\log\\sigma-\\frac12\\log(2\\pi),\\quad\\partial_\\mu\\log\\pi=\\frac{u-\\mu}{\\sigma^2}",
        "密度可以大于1，单个实数动作的概率仍为0。σ必须>0；有推力界时还需要第10章的变换密度。"),
      prose("这个实验未把密度更新直接当成真实小车性能改善。好动作的定义来自同一状态的长期优势；改变均值还会改变后面访问哪些状态，需要完整轨迹推导来处理。")),
    topic("05","derivation",
      proof("任务与正则条件","1 · 参数改变轨迹发生的概率",
        prose("假设初始分布、环境转移与奖励不依赖θ；策略可微、有相应支持，允许交换积分与求导。先取有限T，终止后补零奖励。连续轨迹把下面的求和理解为积分。"),
        equation("p_\\theta(\\tau)=\\rho_0(s_0)\\prod_{t=0}^{T-1}\\pi_\\theta(a_t\\mid s_t)P(s_{t+1},r_t\\mid s_t,a_t),\\qquad J_\\gamma=\\int p_\\theta(\\tau)\\sum_t\\gamma^tr_t\\,d\\tau",
          "策略选择推力；环境产生后继。对小车代价目标，用r=−c；末端代价也计入任务回报。")),
      proof("微积分恒等式","2 · log-derivative把导数变成采样期望",
        equation("\\nabla p_\\theta=p_\\theta\\nabla\\log p_\\theta,\\qquad\\nabla\\log p_\\theta(\\tau)=\\sum_t\\nabla\\log\\pi_\\theta(a_t\\mid s_t)",
          "log将概率乘积变成和；环境不依赖θ，所以它的导数为0。环境直接依赖θ时须补额外项。"),
        equation("\\nabla J_\\gamma=\\mathbb E_{\\tau\\sim p_\\theta}\\left[\\left(\\sum_k\\gamma^kr_k\\right)\\sum_t\\nabla\\log\\pi_\\theta(a_t\\mid s_t)\\right]",
          "原始轨迹级REINFORCE不需要对未知动力学求导；梯度靠当前策略采样估计。")),
      proof("条件期望恒等式","3 · 当前动作不能影响已发生的奖励",
        equation("u_t=\\nabla\\log\\pi_\\theta(a_t\\mid s_t),\\quad\\mathbb E[u_t\\mid H_t]=\\int\\pi_\\theta(a\\mid s_t)\\nabla\\log\\pi_\\theta(a\\mid s_t)\\,da=\\nabla\\int\\pi_\\theta(a\\mid s_t)\\,da=0",
          "Hₜ是选动作前的历史。过去奖励已知，乘score的条件期望为0。连续情形需要前面的积分正则条件。"),
        equation("\\boxed{\\nabla J_\\gamma=\\mathbb E\\left[\\sum_t\\gamma^tG_t\\nabla\\log\\pi_\\theta(a_t\\mid s_t)\\right]}",
          "reward-to-go删除过去奖励。Gₜ从t重新折扣，所以初始折扣目标还需外层γᵗ。γ=1的有限时域没有这项衰减。")),
      proof("条件期望与占用表示","4 · 从回报样本到PG定理",
        equation("\\nabla J_\\gamma=\\frac1{1-\\gamma}\\mathbb E_{s\\sim d_\\gamma^\\pi,a\\sim\\pi}[Q^\\pi(s,a)\\nabla\\log\\pi_\\theta(a\\mid s)]",
          "γ<1、相关值有界时，占用测度dγ(B)=(1−γ)ΣγᵗPr(Sₜ∈B)。连续状态不使用单点概率替代密度；访问变化已由轨迹推导计入。")),
      reading("对数导数与因果性的推导补充",PG)),
    topic("05","baseline",
      equation("\\mathbb E_{a\\sim\\pi}[b(s)\\nabla\\log\\pi(a\\mid s)]=b(s)\\nabla\\int\\pi(a\\mid s)\\,da=0",
        "给定状态不依赖当前动作的baseline不改变期望梯度；动作相关baseline通常需要额外修正。"),
      equation("A^\\pi(s,a)=Q^\\pi(s,a)-V^\\pi(s),\\qquad g=(G-b(s))\\nabla\\log\\pi(a\\mid s)",
        "均值不变，波动会变。Vπ是常用基线，未必是最小方差选择。"),
      baselineLab(),
      prose("本单步例子u∼N(μ,1)、r=−(u+1)²，J=−[(μ+1)²+1]。μ=0时真梯度−2；b=0方差30，b=−2方差18，b=−4方差14，b=+2反而方差50。",
        "最小化单个梯度项的方差给b*=E[∥score∥²G]/E[∥score∥²]，而不是简单平均G。整条轨迹还有跨时刻相关性；学习到的critic也有误差。不要把一次正或负样本更新当作一定改善。")),
    topic("05","actor-critic",
      equation("\\delta_t=r_t+\\gamma m_tV_{old}(s_{t+1})-V_{old}(s_t),\\qquad\\hat A_t=\\delta_t+\\gamma\\lambda c_t\\hat A_{t+1}",
        "GAE反向递推。mₜ表示可否bootstrap；cₜ表示下一条δ是否属于同一段真实轨迹。"),
      gaeLab(),
      table(["边界","m：接最后价值？","c：接下一条δ？"],[["正常继续",1,1],["真正终止",0,0],["外部时间截断",1,0],["rollout切段",1,0]]),
      prose("截断要读取最后真实观察，不能误用自动reset后的新起点。有限时域任务自身结束是终止，需要把剩余时间纳入状态。λ=0给一步TD优势；完整终止轨迹λ=1给G−V。中间λ折中目标长度、采样波动与critic误差。",
        "actor用detach后的优势加权log-density；critic拟合固定目标Vold+Â。共享网络时还要检查两种损失的梯度耦合。"),
      equation("\\theta\\leftarrow\\theta+\\eta_\\pi\\gamma^t\\hat A_t\\nabla_\\theta\\log\\pi_\\theta(a_t\\mid s_t),\\qquad L_V=\\tfrac12(V_\\phi(s_t)-\\operatorname{stopgrad}(V_{old}(s_t)+\\hat A_t))^2",
        "actor与critic有不同训练目标。GAE与连续Gaussian属于原书第9章之外的实践补充。"),
      reading("GAE §2–3",GAE),bookReading("第9章",111)),
    chapterFooter("05","概率密度给连续动作，轨迹概率给正确采样梯度，因果性去过去，baseline改波动，critic与GAE估计未来。能求梯度后，下一章问小梯度意味着什么，以及怎样衡量行为变化。"));
  return()=>{};
}
export function natural(root){
  root.append(chapterHeader("06"),
    topic("06","optimality",
      prose("优化器报告梯度很小，并不等于机器人已经学会。两个奖励分别0和1的动作，若softmax选择好动作的概率p=0.001，则J=p，logit梯度p(1−p)=0.000999；策略仍很差，梯度却很小。"),
      equation("J(\\theta)=p,\\quad p=\\sigma(\\theta),\\quad\\frac{dJ}{d\\theta}=p(1-p)",
        "几乎不采好动作时，普通PG可能改善很慢；若还很少访问关键状态，梯度会进一步受访问分布压低。"),
      table(["结论","需要怎样理解"],[
        ["Stationary","给定参数化中梯度为0或很小"],
        ["Global optimal","在指定策略集合和任务内没有更好的策略"],
        ["表格softmax的特殊结论","仍需要准确梯度、覆盖、步长等对应条件"],
        ["神经Gaussian策略","非凸、近似critic、有限数据；不能继承任意全局保证"],
      ]),
      prose("原书第10章讨论softmax、覆盖与log barrier等特殊结构。这里保留成立条件和反例；机器人策略网络的限制、动作尺度和数据分布必须重新分析。")),
    topic("06","geometry",
      prose("同样把Gaussian均值改0.2 N：标准差1 N时KL=0.02；标准差0.1 N时KL=2。参数看起来改得一样，动作分布变化却相差100倍。优化应关心机器人实际行为变化，而不只看参数的欧氏距离。"),
      geometryLab(),
      equation("D_{KL}(\\mathcal N(\\mu,\\sigma^2)\\Vert\\mathcal N(\\mu+\\Delta\\mu,\\sigma^2))=\\frac{(\\Delta\\mu)^2}{2\\sigma^2},\\qquad F_{\\mu\\mu}=\\frac1{\\sigma^2}",
        "固定方差时是精确式；一般参数变化下KL只在局部近似为Fisher二次型。"),
      equation("F=\\mathbb E[uu^\\top],\\quad u=\\nabla\\log\\pi,\\qquad\\max_\\Delta g^\\top\\Delta\\ \\text{s.t.}\\ \\tfrac12\\Delta^\\top F\\Delta\\le\\kappa",
        "F与g在当前策略/占用下计算。这里只写局部线性目标与局部KL模型。"),
      equation("\\Delta=\\sqrt{\\frac{2\\kappa}{g^\\top F^{-1}g}}F^{-1}g",
        "假设F正定、g≠0、κ>0。实际F可能奇异，需要damping/解线性系统；有限步长后的真实KL仍需检查。")),
    topic("06","compatible",
      equation("\\hat A_w(s,a)=w^\\top u(s,a),\\qquad\\min_w\\mathbb E[(w^\\top u-A)^2]\\ \\Longrightarrow\\ Fw=\\mathbb E[uA]",
        "把score作为优势特征，平方回归的法方程直接给出Fisher方向。期望分布和PG权重必须一致；初始折扣目标的常数可进入步长。"),
      prose("这是兼容函数近似的意义：表示形式与actor梯度匹配，而不是任何准确的critic都等同于自然梯度。用普通神经网络拟合优势、有限样本求解、改变数据分布都会引入额外误差。",
        "在固定σ的一维均值例子，F=1/σ²、局部普通梯度g，未归一化自然方向为σ²g。KL预算固定时允许的均值步长与σ成正比；在小方差状态避免把一个普通大步当成温和更新。"),
      optional("选读：NPG/Q-NPG的速率与误差",
        prose("原书第11章把近似误差与覆盖放进分析。完整regret/速率证明不是连续机器人执行保证，需逐项核对其函数类与数据条件。"),bookReading("第10–11章",119))),
    chapterFooter("06","梯度大小依赖动作与状态覆盖；Fisher衡量局部行为变化，兼容优势回归解释自然方向。接下来把这些工具放入旧批次训练，区分真实回报与可优化代理目标。"));
  return()=>{};
}
export function conservative(root){
  root.append(chapterHeader("07"),
    topic("07","surrogate",
      proof("望远镜求和恒等式","先写真实性能差",
        equation("J(\\pi)-J(\\pi_{old})=\\frac1{1-\\gamma}\\mathbb E_{s\\sim d_\\gamma^\\pi,a\\sim\\pi}[A^{old}(s,a)]",
          "γ<1、价值有界。沿新策略累计r+γVold(s′)−Vold(s)，中间旧价值消去，剩新回报减初始旧价值。这里访问分布仍是新策略的。")),
      proof("旧状态分布近似","才能用旧数据定义surrogate",
        equation("L_{old}(\\pi)=J(\\pi_{old})+\\frac1{1-\\gamma}\\mathbb E_{s\\sim d_\\gamma^{old},a\\sim\\pi}[A^{old}(s,a)]",
          "L与J在旧参数处值和梯度相同；离开旧策略后通常不同。"),
        surrogateLab(),
        prose("设q=0.1、p=0.9：J=1.044，L=1.62；q=0.9、p=0.9：J=1.396，L=0.82。旧数据对后继的访问概率固定为0.5，而新策略已经改变它，L可能在J两侧。")),
      equation("\\mathbb E_{a\\sim\\pi_\\theta(\\cdot\\mid s)}A^{old}(s,a)=\\mathbb E_{a\\sim\\pi_{old}(\\cdot\\mid s)}\\left[\\frac{\\pi_\\theta(a\\mid s)}{\\pi_{old}(a\\mid s)}A^{old}(s,a)\\right]",
        "给定s的动作换测度精确，需要支持覆盖。连续动作使用密度比；它没有把旧状态分布换成新状态分布。")),
    topic("07","trust-region",
      prose("CPI保守地混合旧策略和候选改善策略，减小行为改变；TRPO用KL信赖域组织参数更新。第6章自然梯度是线性surrogate、二次KL近似下的局部方向，实际需要检查KL和代理目标。",
        "这些方法由状态分布变化这一问题推动产生。理论性能界中出现最大的逐状态变化；常用实现优化的是旧访问分布下的平均KL，两者不能互换。"),
      equation("\\pi_{new}=(1-\\eta)\\pi_{old}+\\eta\\pi_{candidate},\\qquad \\bar D=\\mathbb E_{s\\sim d^{old}}D_{KL}(\\pi_{old}\\Vert\\pi_{new})",
        "策略混合与神经参数线性插值不是同一件事。平均KL约束更便于采样估计，但不会控制每个状态。"),
      prose("两个状态权重0.99与0.01，KL分别0与1 nat，平均只有0.01，最大却是1。罕见但重要的接触状态可能发生很大变化，训练平均看起来仍很小；采样平均还存在估计误差。"),
      reading("TRPO：性能差与信赖域",TRPO)),
    topic("07","ppo",
      prose("PPO保留旧批次上的动作ratio与优势，设计一个更方便一阶优化的局部目标：朝改善方向越过阈值后不再额外奖励，朝坏方向仍保留惩罚。这是算法选择，不是从PG定理唯一推出来的公式。"),
      equation("w_t(\\theta)=\\exp(\\log\\pi_\\theta(a_t\\mid s_t)-\\log\\pi_{old}(a_t\\mid s_t)),\\quad L^{clip}=\\hat{\\mathbb E}_t\\min(w_t\\hat A_t,\\operatorname{clip}(w_t,1-\\epsilon,1+\\epsilon)\\hat A_t)",
        "w用来表示概率/密度比，避免与奖励r混淆。训练通常最小化负的这个目标。"),
      ppoLab(),
      equation("\\ell(w,A)=\\begin{cases}A\\min(w,1+\\epsilon),&A\\ge0\\\\A\\max(w,1-\\epsilon),&A<0\\end{cases}",
        "ε=0.2：A=2,w=1.5得2.4；A=−2,w=0.5得−1.6；A=−2,w=1.5仍为−3。"),
      prose("不能说“ratio越界梯度总为0”：正优势w过小、负优势w过大仍保留斜率。clip目标逐样本不高于未裁剪surrogate，但不是新策略真实J的全局下界，也不硬性保证ratio或KL留在某个区间。共享参数、critic与其他样本还会推动已进入平台的动作。"),
      reading("PPO §3、§5",PPO)),
    topic("07","entropy",
      prose("Jensen常在把归一化常数写成可优化期望时出现。log是凹函数：先平均再取log位于平均log之上。拖动两个数，看到曲线与弦的差距；这和PPO的min设计是不同步骤。"),
      equation("\\mathbb E\\log X\\le\\log\\mathbb EX\\quad(X>0),\\qquad Z=\\sum_a e^{Q(a)/\\alpha}",
        "这里先用有限动作做精确数学热身，α>0。机器人连续动作的熵是相应密度下的微分熵。"),
      ...entropyLab(),
      proof("插入概率＋凹log不等式","奖励加熵怎样出现",
        equation("\\alpha\\log Z=\\alpha\\log\\mathbb E_{a\\sim\\pi}\\frac{e^{Q(a)/\\alpha}}{\\pi(a)}\\ge\\mathbb E_\\pi Q+\\alpha H(\\pi)",
          "先假设π覆盖所有动作，零概率可取极限。不是随意把log移进期望。"),
        equation("\\pi^*(a)=e^{Q(a)/\\alpha}/Z,\\qquad \\alpha\\log Z-(\\mathbb E_\\pi Q+\\alpha H)=\\alpha D_{KL}(\\pi\\Vert\\pi^*)",
          "差距恰为温度×KL，π=softmax时达到上界。熵改变优化目标，不是无条件提高原始奖励。")),
      equation("\\alpha\\log\\sum_a e^{Q(a)/\\alpha}=m+\\alpha\\log\\sum_a e^{(Q(a)-m)/\\alpha},\\quad m=\\max_aQ(a)",
        "稳定log-sum-exp。Q=(1000,1002)、α=1得到1002.126928；直接指数会overflow。"),
      reading("最大熵RL与固定动力学推断的补充","https://arxiv.org/html/1805.00909v3#S3.SS2")),
    topic("07","practice",
      table(["步骤","固定/更新的对象","为什么"],[
        ["采集rollout","冻结πold、保存旧log-density、V、真实末观察","数据来自哪一个策略必须可追溯"],
        ["估计优势","算GAE与critic目标，随后detach","不从actor权重反传进目标"],
        ["多轮minibatch","只更新当前actor/critic；旧分母不变","避免ratio每轮变回1"],
        ["连续联合动作","各维log-density先求和，再计算ratio","联合动作比不是每维独立clip"],
        ["标准化与范数裁剪","记录batch范围和优化步变化","有限batch中心化可能改变优势符号；不保证精确无偏"],
        ["KL与clip fraction","检查行为变化，必要时停止本批","clip没有硬约束KL"],
        ["重新采样与评估","结束本批后采新轨迹；单独评估","代理loss变好不等于任务执行变好"],
      ]),
      h("pre",{class:"algorithm-flow"},h("code",{},"采旧策略轨迹 → 算优势和return → 冻结旧量\n新log-density → ratio → actor/critic/entropy损失\n多轮minibatch并监测KL → 重新采样 → 独立执行评估")),
      optional("选读：其他保守优化与完整训练",
        prose("原书§12.3讨论正交化与逐行归一化；主线不展开算法家谱。这里的曲线与算例没有运行神经PPO训练，Python训练模块仍保留；完整机器人训练需第10章的接口和验收。"),bookReading("第12章",141))),
    chapterFooter("07","性能差是恒等式，固定旧访问是近似，动作ratio在固定状态下精确，PPO clip是局部目标设计；Jensen/KL解释额外熵目标。旧数据和变量固定后，还必须用新策略真正执行验收。"));
  return()=>{};
}
