import {h} from "../ui/dom.js";
import {chapterHeader,chapterFooter,topic,prose,equation,proof,table,optional,bookReading,reading} from "./shell.js";
import {controlLab,goalLab} from "./labs.js";
import {THESIS} from "./curriculum.js";
const LQR="https://underactuated.mit.edu/lqr.html";
export function imitation(root){
  root.append(chapterHeader("08"),
    topic("08","bc",
      prose("PPO从交互回报学习；Behavior Cloning（BC）用专家状态和推力做动作回归，不直接优化环境回报。",
        "专家uE=−p−v：p=0.5、v=−1时用+0.5刹车；v=+1时用−1.5拉回。省略速度会把两种标签平均。"),
      equation("L_{BC}(\\theta)=\\frac1N\\sum_{i=1}^N\\|\\mu_\\theta(s_i)-u_E(s_i)\\|^2,\\qquad L_{NLL}=-\\frac1N\\sum_i\\log\\pi_\\theta(u_E(s_i)\\mid s_i)",
        "固定方差Gaussian的NLL等价于平方误差；专家动作依赖剩余时间时，学生也须观察它。"),
      table(["监督来源","训练信号","不保证"],[
        ["BC","专家给的动作标签","偏离示范后的控制正确"],
        ["RL","环境累计奖励","探索充分或全局最优"],
        ["LQR","已知动力学与reward","未知、非线性或受约束模型的精确最优"],
      ])),
    topic("08","shift",
      prose("相同模型与初态下，开环回放专家推力可复现轨迹。t=2的速度扰动或质量变化后，反馈按新状态调整，回放仍执行旧指令。",
        "完整状态、匹配函数类与充分示范覆盖下，线性BC可精确恢复专家。"),
      controlLab({prefix:"imitation",imitation:true}),
      equation("s_{t+1}^{student}=f(s_t^{student},\\mu_\\theta(s_t^{student})),\\qquad d^{student}\\ne d^{expert}",
        "动作误差改变下一状态，后续预测偏离示范分布；需在学生访问的状态验证。")),
    topic("08","interactive",
      prose("DAgger让学生执行，将新状态交给专家标注后加入训练集；需要持续交互和可调用专家。",
        "DAgger聚合动作标签；AggreVaTe用专家Q评价候选动作。第13章还讨论Hybrid IL。"),
      table(["设置","可用数据/访问","必须检查"],[
        ["纯离线BC","固定示范状态与专家动作","新状态覆盖与观测完整性"],
        ["DAgger","学生交互＋新状态专家动作","专家可调用、状态可标注"],
        ["AggreVaTe","专家Q估计/访问","后续return信息的可用性"],
        ["Hybrid IL","混合数据或模型访问","额外数据/模型接口是否可用"],
      ]),
      reading("DAgger原论文","https://proceedings.mlr.press/v15/ross11a/ross11a.pdf")),
    topic("08","reward",
      prose("逆强化学习从行为推断奖励。同一停车示范可符合快速到达、省力或舒适刹车，有限示范通常不能唯一确定奖励。",
        "最大熵模型以回报和熵解释轨迹偏好，依赖动力学与推断假设；第7章Jensen/熵可辅助理解。"),
      equation("p_r(\\tau)\\propto p_{dynamics}(\\tau)\\exp\\left(\\sum_t r(s_t,a_t)\\right)",
        "随机后果由动力学决定；轨迹模型需指定奖励尺度、特征和分布假设。"),
      bookReading("第13章",161)),
    chapterFooter("08","BC学习专家动作；交互模仿补充新状态，逆强化学习推断reward。"));
  return()=>{};
}
export function lqr(root){
  root.append(chapterHeader("09"),
    topic("09","dynamics",
      prose("小车是1 kg点质量，每Δt=0.5 s保持恒力；位置、速度、推力连续，时间离散采样。",
        "驶向目标时需提前刹车，离开目标时需拉回；停车要求位置误差与速度同时接近0。"),
      equation("e_t=p_t-g,\\quad x_t=\\begin{bmatrix}e_t\\\\v_t\\end{bmatrix},\\quad x_{t+1}=Ax_t+Bu_t,\\quad A=\\begin{bmatrix}1&\\Delta t\\\\0&1\\end{bmatrix},\\quad B=\\begin{bmatrix}\\Delta t^2/(2m)\\\\\\Delta t/m\\end{bmatrix}",
        "e：m，v：m/s，u：N。恒力改变速度，位置按周期内的运动积分更新。"),
      prose("本节先用已知、确定性的模型求最优策略。")),
    topic("09","objective",
      equation("r(x,u)=-x^\\top Mx-u^\\top Ru,\\quad r_H(x)=-x^\\top M_Hx,\\quad M,M_H\\succeq0,\\ R\\succ0",
        "reward惩罚位置误差、速度与用力。"),
      equation("J(\\pi)=\\mathbb E_\\pi\\left[\\sum_{t=0}^{H-1}r(x_t,u_t)+r_H(x_H)\\right],\\qquad\\max_\\pi J(\\pi)",
        "γ=1，末端未停稳会降低return；这是软惩罚。"),
      table(["默认参数","数值","含义"],[
        ["起点与目标","x₀=(2,0)，g=0","从2 m静止出发，目标静止"],
        ["模型","m=1，Δt=0.5","无摩擦点质量、每半秒决策"],
        ["时域","H=6","最大化3秒内的return"],
        ["M / R","diag(1,0.2) / 0.5","位置、速度与推力相对权重"],
        ["M_H","diag(20,10)","末端更重地惩罚未停靠"],
      ]),
      prose("增大R让策略更省力，可能到达更慢；增大H给它更多时间。比较策略时固定任务和reward。")),
    topic("09","riccati",
      proof("二次价值闭包","1 · Bellman连续最大化",
        equation("V_H^*(x)=-x^\\top M_Hx,\\quad Q_t^*(x,u)=r(x,u)+V_{t+1}^*(Ax+Bu),\\quad V_t^*(x)=\\max_uQ_t^*(x,u)",
          "取Vₜ*=−xᵀPₜx；Pₜ⪰0，默认权重使Pₜ≻0。"),
        equation("S_t=R+B^\\top P_{t+1}B,\\qquad\\nabla_uQ_t^*(x,u)=-2S_tu-2B^\\top P_{t+1}Ax=0",
          "R≻0、Pₜ₊₁⪰0保证Sₜ≻0，故无约束动作的最大点唯一。")),
      proof("完成平方并代回","2 · 得到策略与价值",
        equation("-x^\\top Mx-u^\\top Ru-(Ax+Bu)^\\top P_{t+1}(Ax+Bu)=-x^\\top P_tx-(u+K_tx)^\\top S_t(u+K_tx)",
          "第二项非正；u=−Kₜx时为0，得到Vₜ*=−xᵀPₜx。"),
        equation("K_t=S_t^{-1}B^\\top P_{t+1}A,\\qquad\\boxed{u_t^*=-K_tx_t}",
          "求K时解线性系统，比显式求逆稳定。"),
        equation("P_t=M+A^\\top P_{t+1}A-A^\\top P_{t+1}B S_t^{-1}B^\\top P_{t+1}A,\\qquad P_H=M_H",
          "从H−1递推到0；等价式Pₜ=M+KₜᵀRKₜ+(A−BKₜ)ᵀPₜ₊₁(A−BKₜ)。")),
      prose("P的少量系数描述所有状态的V，完成平方直接求连续动作；精确性依赖线性模型、二次reward与无约束动作。")),
    topic("09","feedback",
      prose("默认K₀=(0.929151,1.446994)，首步推力−1.858302 N：先向左加速，再用正推力刹车。末位置误差约0.001310 m，末速度约−0.058024 m/s。",
        "调初速度、R或H后重算P/K、轨迹和return；“下一步”逐步执行反馈，相平面黑点表示位置误差、速度均为0。"),
      controlLab(),
      equation("J^*=V_0^*(x_0)=-x_0^\\top P_0x_0=-12.500159",
        "默认模型下，最优轨迹return等于V₀*；负数也越大越好。"),
      table(["同一默认任务","return（越大越好）","解释"],[
        ["不控制 u=0","−104","停在2 m，未到目标"],
        ["只看位置 u=−e","−193.108372","忽略速度，冲过目标并振荡"],
        ["固定PD u=−e−v","−17.774408","含速度反馈，未最大化此有限return"],
        ["有限时域LQR","−12.500159","当前无约束模型的最大return"],
      ])),
    topic("09","limits",
      equation("\\rho(A-BK)<1",
        "固定反馈、确定性离散线性系统的渐近稳定条件；ρ为最大特征值模。"),
      prose("Δt=0.5时，K=(1,0)的ρ=1.060660，振荡放大；K=(1,1)的ρ=0.790569，振荡衰减。有限时域Kₜ随时间变化，末态未必为0；每步ρ<1也不足以保证时变系统稳定。",
        "限幅施加clip(−Kx,−1,1)，通常失去无约束最优性；约束任务需重求解，如MPC。质量变化时控制器仍按m=1计算；速度脉冲后反馈读取实际状态。"),
      table(["超出理想模型","应该重新检查"],[
        ["力/扭矩限制","可行域、饱和、约束规划与评价"],
        ["非线性机械系统","局部线性化范围与轨迹跟踪"],
        ["传感器和延迟","状态估计、观测完整性、控制频率"],
        ["无限时域","稳定Riccati解需stabilizability/detectability"],
      ]),
      optional("选读：LQR策略优化、SDP、SLS",
        prose("§14.3–14.5讨论凸规划、PG/NPG/Gauss–Newton和系统级综合；其优化保证依赖LQR结构。"),bookReading("第14章",173)),
      reading("连续控制推导与模型边界",LQR)),
    chapterFooter("09","Riccati用二次V和连续最大化求反馈，可由轨迹return验算；限幅、未知模型和非线性需重新检验。"));
  return()=>{};
}
export function robotics(root){
  root.append(chapterHeader("10"),
    topic("10","interface",
      prose("环境接口定义观测、动作单位、步进、回报与成功条件。",
        "先用解析控制器校准动力学与reward，再引入未知模型、动作限制和多目标。"),
      table(["接口","小车定义","设备还需定义"],[
        ["状态/观测","(p−g,v)；有限H加剩余时间","传感器、延迟、状态估计、接触模式"],
        ["动作","每0.5秒施加u；归一化z∈[−1,1]时u=u_max z","控制频率、力/扭矩单位、执行器限幅"],
        ["reward","r=−(e²+0.2v²+Ru²)，终止步加入r_H","全部方法使用相同原始reward评价"],
        ["初态与目标","位置、速度、目标的分布","训练/测试目标与初态划分"],
        ["成功","例如|p−g|≤0.1 m且|v|≤0.1 m/s","是否需持续停稳、碰撞或任务失败"],
        ["边界","任务H终止；外部截断保留bootstrap","reset观测不是上一回合末态"],
      ]),
      prose("最大return不保证成功，高速过点不算停稳。分别记录任务终止、episode时限与rollout长度。")),
    topic("10","algorithms",
      proof("变换密度","有界动作的log概率",
        equation("z=\\mu_\\theta(s)+\\sigma_\\theta(s)\\epsilon,\\quad\\epsilon\\sim\\mathcal N(0,I),\\qquad u=u_{max}\\tanh z",
          "无界z经tanh映射为合法推力；σ用logσ或正值变换参数化。"),
        equation("\\log\\pi_u(u\\mid s)=\\log\\mathcal N(z;\\mu,\\sigma^2)-\\log u_{max}-\\log(1-\\tanh^2z)",
          "一维Jacobian修正，多维求和；饱和附近须稳定计算log项。"),
        prose("固定动作和变换时，PPO密度比中Jacobian相消；SAC熵项仍须修正密度。硬裁剪Gaussian在边界有概率质量，不能直接套普通Gaussian密度。")),
      table(["方法","数据与actor目标","区别"],[
        ["连续PPO","当前策略rollout；固定旧批次，多轮优势加权ratio更新","clipping不限制动作或硬约束KL"],
        ["SAC","新增交互＋replay；随机actor优化奖励加熵","off-policy可继续交互"],
        ["LQR","已知模型求Riccati反馈","解析求解，无需神经网络训练"],
      ]),
      equation("y=r+\\gamma m\\left[\\min_i Q_{\\bar\\phi_i}(s',u')-\\alpha\\log\\pi_\\theta(u'\\mid s')\\right],\\quad u'\\sim\\pi_\\theta",
        "双critic SAC目标；目标量detach，真终止m=0遮去尾值，外部截断m=1。"),
      equation("J_\\pi(\\theta)=\\mathbb E[\\min_iQ_{\\phi_i}(s,u)-\\alpha\\log\\pi_\\theta(u\\mid s)],\\qquad\\max_\\theta J_\\pi(\\theta)",
        "重参数化保留动作经critic的梯度。SAC最大化奖励加熵，比较LQR时另报无熵原始return。"),
      reading("SAC：核心方程与连续策略","https://spinningup.openai.com/en/latest/algorithms/sac.html"),
      reading("SAC原论文：Appendix C变换密度","https://arxiv.org/pdf/1801.01290")),
    topic("10","gcrl",
      prose("目标条件RL把g输入策略和价值。p=1.5、v=0时，目标0 m和3 m需要相反推力；g改变任务，不改变动力学。拖动目标观察反馈。",
        "停车要求位置达标且速度接近0；机械臂目标可含位姿、接触或物体状态。先定义目标表示与成功集合。"),
      goalLab(),
      equation("\\pi_\\theta(u\\mid s,g),\\quad Q(s,u,g),\\quad r_g(s,u,s'),\\quad P(s'\\mid s,u)\\ \\text{不随 }g\\text{改变}",
        "假设g仅表示任务，P不变；奖励与终止按g定义。"),
      equation("u=-K_t\\begin{bmatrix}p-g\\\\v\\end{bmatrix}",
        "这是解析目标条件反馈；期望速度非零时用v−v_goal，并重定义跟踪任务。"),
      reading("Ben Eysenbach 博士论文：目标条件学习",THESIS)),
    topic("10","relabel",
      prose("HER保留(s,u,s′)，将轨迹改标为有效已实现目标g′，重算奖励与目标依赖终止。",
        "停车要求停稳，高速经过的位置不算成功目标。目标空间为(p,v)时可用实际完整状态改标；目标速度限定0时，只选满足停稳条件的后继。保留物理失败和reset边界。"),
      equation("r_{g'}=\\mathbf1\\{|p'-g'|\\le\\varepsilon_p,\\ |v'|\\le\\varepsilon_v\\},\\qquad (s,u,s')\\ \\text{保持不变}",
        "此处用成功指示reward；新目标若终止则截去后缀，保留原日志与reset边界。"),
      table(["同一后继","若g′=0.5且阈值0.1","解释"],[
        ["p′=0.5,v′=0.8","未成功","只到位置，仍然太快"],
        ["p′=0.52,v′=0.05","成功并终止","位置与速度都进入集合"],
        ["交点p相同、v不同","不能直接stitch","完整Markov状态不匹配"],
      ]),
      equation("d_\\gamma^\\pi(B\\mid s,a)=(1-\\gamma)\\sum_{k\\ge0}\\gamma^k\\Pr_\\pi(S_{t+k+1}\\in B\\mid s_t=s,a_t=a)",
        "0≤γ<1；B为目标集合。它统计未来占用，允许重复到访；有密度时可写dγ(g)。"),
      prose("对比critic用未来状态作正样本、目标作负样本；平衡分类的Bayes最优odds对应dγ(g|s,a)/p(g)。须明确未来策略，并区分占用奖励、到达奖励和首次到达终止。",
        "表示、分类与对比方法连接神经GCRL；表示、critic/actor训练和远目标泛化需分别验证。"),
      optional("论文选读：C-learning、Contrastive RL与SoRB",
        prose("论文第2–4章、附录B讨论未来分布、目标条件actor和路标搜索。路标须含充分状态，局部控制和搜索边须能实际执行；几何接近不保证可控。"),
        reading("Ben论文 §2–4、附录B",THESIS))),
    topic("10","evaluation",
      table(["验收问题","记录证据"],[
        ["是否真的执行","训练算法、环境步数、种子、超参数与模型版本"],
        ["任务是否一致","动力学、原始reward、动作界、初态与目标分布"],
        ["是否停稳","位置/速度随时间、成功率、return、峰值推力"],
        ["扰动是否可应对","质量误差、外力、观测噪声、时延、动作饱和"],
        ["目标是否泛化","训练/测试goal划分、未见目标、初速度、距离、覆盖与表示误差"],
        ["比较是否公平","相同交互预算、多种子、消融与不确定性"],
      ]),
      prose("未见目标测试时，测试goal不进入训练或HER改标；训练配置、模型与回放数据均记录来源。",
        "先验算LQR，再用相同任务比较PPO；加入约束、未知模型后比较SAC，最后测试多目标GCRL。每次只增加一个困难，固定其余评价条件。")),
    chapterFooter("10","完整状态、正确动作密度、数据来源和目标定义决定机器人任务；比较须用相同reward与真实执行结果。"));
  return()=>{};
}
